/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author jdfer
 */
public class MenúPrincipal extends javax.swing.JFrame{
    Border borde = BorderFactory.createLineBorder(Color.blue);
    
    public MenúPrincipal() {
        initComponents();
        panelesOp.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOpciones = new javax.swing.JPanel();
        botonAmbulancias = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        botonAmbulatorios = new javax.swing.JLabel();
        botonPacientes = new javax.swing.JLabel();
        botonClinica = new javax.swing.JLabel();
        panelesOp = new javax.swing.JTabbedPane();
        panelClinica = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonHOME3 = new javax.swing.JButton();
        fondo1 = new javax.swing.JLabel();
        panelAmbulatorios = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        botonHOME2 = new javax.swing.JButton();
        fondo2 = new javax.swing.JLabel();
        panelAmbulancias = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        botonHOME1 = new javax.swing.JButton();
        fondo3 = new javax.swing.JLabel();
        panelPacientes = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        botonHOME = new javax.swing.JButton();
        fondo4 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelOpciones.setBackground(new java.awt.Color(255, 255, 255));

        botonAmbulancias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton ambulancias.jpg"))); // NOI18N
        botonAmbulancias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAmbulanciasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAmbulanciasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAmbulanciasMouseExited(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N

        botonAmbulatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton ambulatorio.jpg"))); // NOI18N
        botonAmbulatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAmbulatoriosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAmbulatoriosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAmbulatoriosMouseExited(evt);
            }
        });

        botonPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton pacientes.jpg"))); // NOI18N
        botonPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonPacientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonPacientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonPacientesMouseExited(evt);
            }
        });

        botonClinica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton clinica.jpg"))); // NOI18N
        botonClinica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonClinicaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonClinicaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonClinicaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelOpcionesLayout = new javax.swing.GroupLayout(panelOpciones);
        panelOpciones.setLayout(panelOpcionesLayout);
        panelOpcionesLayout.setHorizontalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOpcionesLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(logo))
                    .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(botonClinica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonAmbulancias, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botonAmbulatorios))
                .addGap(0, 11, Short.MAX_VALUE))
        );
        panelOpcionesLayout.setVerticalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addGap(32, 32, 32)
                .addComponent(botonClinica, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(botonAmbulatorios)
                .addGap(28, 28, 28)
                .addComponent(botonAmbulancias, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(botonPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 670));

        panelClinica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("PANEL CLINICA");
        panelClinica.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, -1, -1));

        botonHOME3.setText("HOME");
        botonHOME3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHOME3ActionPerformed(evt);
            }
        });
        panelClinica.add(botonHOME3, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 313, -1, -1));

        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Wallpaper.jpg"))); // NOI18N
        panelClinica.add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 660));

        panelesOp.addTab("Clínica", panelClinica);

        panelAmbulatorios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("PANEL AMBULATORIOS");
        panelAmbulatorios.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        botonHOME2.setText("HOME");
        botonHOME2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHOME2ActionPerformed(evt);
            }
        });
        panelAmbulatorios.add(botonHOME2, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 313, -1, -1));

        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Wallpaper.jpg"))); // NOI18N
        panelAmbulatorios.add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 660));

        panelesOp.addTab("Ambulatorios", panelAmbulatorios);

        panelAmbulancias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("PANEL AMBULANCIAS");
        panelAmbulancias.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        botonHOME1.setText("HOME");
        botonHOME1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHOME1ActionPerformed(evt);
            }
        });
        panelAmbulancias.add(botonHOME1, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 313, -1, -1));

        fondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Wallpaper.jpg"))); // NOI18N
        panelAmbulancias.add(fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 660));

        panelesOp.addTab("Ambulancias", panelAmbulancias);

        panelPacientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("PANEL PACIENTES");
        panelPacientes.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 248, -1, -1));

        botonHOME.setText("HOME");
        botonHOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHOMEActionPerformed(evt);
            }
        });
        panelPacientes.add(botonHOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 16, -1, -1));

        fondo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Wallpaper.jpg"))); // NOI18N
        panelPacientes.add(fondo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 660));

        panelesOp.addTab("Pacientes", panelPacientes);

        getContentPane().add(panelesOp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, -30, 700, 690));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Wallpaper.jpg"))); // NOI18N
        fondo.setText("jLabel1");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 1000, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonClinicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonClinicaMouseClicked
        panelesOp.setVisible(true);
        panelesOp.setSelectedIndex(0);
    }//GEN-LAST:event_botonClinicaMouseClicked

    private void botonClinicaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonClinicaMouseEntered
        // TODO add your handling code here:
        botonClinica.setBorder(borde);
    }//GEN-LAST:event_botonClinicaMouseEntered

    private void botonClinicaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonClinicaMouseExited
        // TODO add your handling code here:
        botonClinica.setBorder(null);
    }//GEN-LAST:event_botonClinicaMouseExited

    private void botonAmbulatoriosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAmbulatoriosMouseEntered
        // TODO add your handling code here:
        botonAmbulatorios.setBorder(borde);
    }//GEN-LAST:event_botonAmbulatoriosMouseEntered

    private void botonAmbulatoriosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAmbulatoriosMouseExited
        // TODO add your handling code here:
        botonAmbulatorios.setBorder(null);
    }//GEN-LAST:event_botonAmbulatoriosMouseExited

    private void botonAmbulanciasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAmbulanciasMouseEntered
        // TODO add your handling code here:
        botonAmbulancias.setBorder(borde);
    }//GEN-LAST:event_botonAmbulanciasMouseEntered

    private void botonAmbulanciasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAmbulanciasMouseExited
        // TODO add your handling code here:
        botonAmbulancias.setBorder(null);
    }//GEN-LAST:event_botonAmbulanciasMouseExited

    private void botonPacientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPacientesMouseEntered
        // TODO add your handling code here:
        botonPacientes.setBorder(borde);
    }//GEN-LAST:event_botonPacientesMouseEntered

    private void botonPacientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPacientesMouseExited
        // TODO add your handling code here:
        botonPacientes.setBorder(null);
    }//GEN-LAST:event_botonPacientesMouseExited

    private void botonAmbulatoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAmbulatoriosMouseClicked
        panelesOp.setVisible(true);
        panelesOp.setSelectedIndex(1);
    }//GEN-LAST:event_botonAmbulatoriosMouseClicked

    private void botonAmbulanciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAmbulanciasMouseClicked
        panelesOp.setVisible(true);
        panelesOp.setSelectedIndex(2);
    }//GEN-LAST:event_botonAmbulanciasMouseClicked

    private void botonPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPacientesMouseClicked
        panelesOp.setVisible(true);
        panelesOp.setSelectedIndex(3);
    }//GEN-LAST:event_botonPacientesMouseClicked

    private void botonHOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHOMEActionPerformed
        // TODO add your handling code here:
        panelesOp.setVisible(false);
    }//GEN-LAST:event_botonHOMEActionPerformed

    private void botonHOME1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHOME1ActionPerformed
        // TODO add your handling code here:
        panelesOp.setVisible(false);
    }//GEN-LAST:event_botonHOME1ActionPerformed

    private void botonHOME2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHOME2ActionPerformed
        // TODO add your handling code here:
        panelesOp.setVisible(false);
    }//GEN-LAST:event_botonHOME2ActionPerformed

    private void botonHOME3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHOME3ActionPerformed
        // TODO add your handling code here:
        panelesOp.setVisible(false);
    }//GEN-LAST:event_botonHOME3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenúPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenúPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenúPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenúPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenúPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botonAmbulancias;
    private javax.swing.JLabel botonAmbulatorios;
    private javax.swing.JLabel botonClinica;
    private javax.swing.JButton botonHOME;
    private javax.swing.JButton botonHOME1;
    private javax.swing.JButton botonHOME2;
    private javax.swing.JButton botonHOME3;
    private javax.swing.JLabel botonPacientes;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel fondo3;
    private javax.swing.JLabel fondo4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panelAmbulancias;
    private javax.swing.JPanel panelAmbulatorios;
    private javax.swing.JPanel panelClinica;
    private javax.swing.JPanel panelOpciones;
    private javax.swing.JPanel panelPacientes;
    private javax.swing.JTabbedPane panelesOp;
    // End of variables declaration//GEN-END:variables
}
