/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import Controller.*;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
/**
 *
 * @author jdfer
 */
public class MenúPrincipal extends javax.swing.JFrame{
    Border borde = BorderFactory.createLineBorder(Color.blue);
    Border bordeAmarillo = BorderFactory.createLineBorder(Color.yellow);
    CRegistro cRegistro = new CRegistro();
    CVentana controlVentana = new CVentana(this);
    ArrayList<String> listaMecanicos = new ArrayList<>();
    CClinica controlClinica;
    CSistema controlSistema;
    IniciarSesión iniciarSesion;
    
    public MenúPrincipal() {
        initComponents();
    }
    
    public MenúPrincipal(CSistema controlSistema,CClinica controlClinica, IniciarSesión iniciarSesion){
        initComponents();
        panelesOp.setVisible(true);
        controlVentana.iniciarVentana(this,"src/imagenes/logo(1).png");
        this.controlSistema=controlSistema;
        this.controlClinica=controlClinica;
        this.iniciarSesion=iniciarSesion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelesOp = new javax.swing.JTabbedPane();
        panelHome = new javax.swing.JPanel();
        botonCerrarSesion = new javax.swing.JButton();
        fondoHome = new javax.swing.JLabel();
        panelClinica = new javax.swing.JPanel();
        bhClinica = new javax.swing.JButton();
        pestClinica = new javax.swing.JTabbedPane();
        panelMostrarAmbulatorios = new javax.swing.JPanel();
        panelInformacionClinica = new javax.swing.JPanel();
        labelInformacionClinica = new javax.swing.JLabel();
        labelNombreClinica = new javax.swing.JLabel();
        labelNombre_DeLaClinica = new javax.swing.JLabel();
        labelRIFClinica = new javax.swing.JLabel();
        labelRIF_DeLaClinica = new javax.swing.JLabel();
        labelTelfClinica = new javax.swing.JLabel();
        labelTelf_DeLaClinica = new javax.swing.JLabel();
        labelCiudadClinica = new javax.swing.JLabel();
        labelCiudad_DeLaClinca = new javax.swing.JLabel();
        labelEstadoClinica = new javax.swing.JLabel();
        labelEstado_DeLaClinica = new javax.swing.JLabel();
        labelDirClinica = new javax.swing.JLabel();
        labelDir_DeLaClinica = new javax.swing.JLabel();
        botonModClinica = new javax.swing.JButton();
        panelRegistrarAmbulatorio = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreAmbulatorio = new javax.swing.JTextField();
        labelRIF = new javax.swing.JLabel();
        txt8RIF = new javax.swing.JTextField();
        labelPrivada = new javax.swing.JLabel();
        guion1 = new javax.swing.JLabel();
        txt1RIF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelf1 = new javax.swing.JTextField();
        labelTelf = new javax.swing.JLabel();
        guion2 = new javax.swing.JLabel();
        txtTelf2 = new javax.swing.JTextField();
        labelDir = new javax.swing.JLabel();
        labelCiudad = new javax.swing.JLabel();
        txtDir = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        labelEstado = new javax.swing.JLabel();
        cboEstado = new javax.swing.JComboBox<>();
        botonRegistrar = new javax.swing.JButton();
        botonVaciar = new javax.swing.JButton();
        panelAsociarTaller = new javax.swing.JPanel();
        labelNombreTaller = new javax.swing.JLabel();
        solicitudTaller = new javax.swing.JLabel();
        txtNombreTaller = new javax.swing.JTextField();
        labelRIFTaller = new javax.swing.JLabel();
        txt8RIFTaller = new javax.swing.JTextField();
        labelPrivada1 = new javax.swing.JLabel();
        guion3 = new javax.swing.JLabel();
        txt1RIFTaller = new javax.swing.JTextField();
        txtTelf1_Taller = new javax.swing.JTextField();
        labelTelf1 = new javax.swing.JLabel();
        guion4 = new javax.swing.JLabel();
        txtTelf2_Taller = new javax.swing.JTextField();
        labelDir_Taller = new javax.swing.JLabel();
        labelCiudad_Taller = new javax.swing.JLabel();
        txtDir_Taller = new javax.swing.JTextField();
        txtCiudad_Taller = new javax.swing.JTextField();
        labelEstado_Taller = new javax.swing.JLabel();
        cboEstado_Taller = new javax.swing.JComboBox<>();
        botonAsociar = new javax.swing.JButton();
        botonVaciar_Taller = new javax.swing.JButton();
        txtNombreMecanico = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonAgregarMecanico = new javax.swing.JButton();
        fondoClinica = new javax.swing.JLabel();
        panelAmbulatorios = new javax.swing.JPanel();
        bhAmbulatorios = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        fondoAmbulatorios = new javax.swing.JLabel();
        panelAmbulancias = new javax.swing.JPanel();
        bhAmbulancias = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        fondoAmbulancias = new javax.swing.JLabel();
        panelPacientes = new javax.swing.JPanel();
        bhPacientes = new javax.swing.JButton();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        fondoPacientes = new javax.swing.JLabel();
        panelOpciones = new javax.swing.JPanel();
        botonAmbulancias = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        botonAmbulatorios = new javax.swing.JLabel();
        botonPacientes = new javax.swing.JLabel();
        botonClinica = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonCerrarSesion.setBackground(new java.awt.Color(255, 0, 51));
        botonCerrarSesion.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        botonCerrarSesion.setText("Cerrar sesión");
        botonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarSesionActionPerformed(evt);
            }
        });
        panelHome.add(botonCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, -1, -1));

        fondoHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Wallpaper.jpg"))); // NOI18N
        panelHome.add(fondoHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 660));

        panelesOp.addTab("Home", panelHome);

        panelClinica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bhClinica.setBackground(new java.awt.Color(51, 51, 255));
        bhClinica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoHome.png"))); // NOI18N
        bhClinica.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bhClinica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bhClinicaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bhClinicaMouseExited(evt);
            }
        });
        bhClinica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhClinicaActionPerformed(evt);
            }
        });
        panelClinica.add(bhClinica, new org.netbeans.lib.awtextra.AbsoluteConstraints(781, 13, 70, 60));

        pestClinica.setBackground(new java.awt.Color(153, 204, 255));
        pestClinica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pestClinica.setOpaque(true);

        panelMostrarAmbulatorios.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelMostrarAmbulatoriosLayout = new javax.swing.GroupLayout(panelMostrarAmbulatorios);
        panelMostrarAmbulatorios.setLayout(panelMostrarAmbulatoriosLayout);
        panelMostrarAmbulatoriosLayout.setHorizontalGroup(
            panelMostrarAmbulatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 803, Short.MAX_VALUE)
        );
        panelMostrarAmbulatoriosLayout.setVerticalGroup(
            panelMostrarAmbulatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );

        pestClinica.addTab("Ambulatorios", panelMostrarAmbulatorios);

        panelInformacionClinica.setBackground(new java.awt.Color(255, 255, 255));

        labelInformacionClinica.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        labelInformacionClinica.setText("Información de la clínica");

        labelNombreClinica.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelNombreClinica.setText("Nombre:");

        labelNombre_DeLaClinica.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        labelRIFClinica.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelRIFClinica.setText("RIF:");

        labelRIF_DeLaClinica.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        labelTelfClinica.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTelfClinica.setText("Teléfono:");

        labelTelf_DeLaClinica.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        labelCiudadClinica.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelCiudadClinica.setText("Ciudad:");

        labelCiudad_DeLaClinca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        labelEstadoClinica.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelEstadoClinica.setText("Estado:");

        labelEstado_DeLaClinica.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        labelDirClinica.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelDirClinica.setText("Dirección:");

        labelDir_DeLaClinica.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        botonModClinica.setBackground(new java.awt.Color(153, 204, 255));
        botonModClinica.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonModClinica.setText("Modificar datos");
        botonModClinica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModClinicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInformacionClinicaLayout = new javax.swing.GroupLayout(panelInformacionClinica);
        panelInformacionClinica.setLayout(panelInformacionClinicaLayout);
        panelInformacionClinicaLayout.setHorizontalGroup(
            panelInformacionClinicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacionClinicaLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(panelInformacionClinicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInformacionClinicaLayout.createSequentialGroup()
                        .addComponent(labelNombreClinica)
                        .addGap(18, 18, 18)
                        .addComponent(labelNombre_DeLaClinica, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInformacionClinicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelInformacionClinicaLayout.createSequentialGroup()
                            .addComponent(labelDirClinica)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(labelDir_DeLaClinica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(panelInformacionClinicaLayout.createSequentialGroup()
                            .addComponent(labelEstadoClinica)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(labelEstado_DeLaClinica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(panelInformacionClinicaLayout.createSequentialGroup()
                            .addComponent(labelCiudadClinica)
                            .addGap(18, 18, 18)
                            .addComponent(labelCiudad_DeLaClinca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(panelInformacionClinicaLayout.createSequentialGroup()
                            .addComponent(labelTelfClinica)
                            .addGap(18, 18, 18)
                            .addComponent(labelTelf_DeLaClinica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(panelInformacionClinicaLayout.createSequentialGroup()
                            .addComponent(labelRIFClinica)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(labelRIF_DeLaClinica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(panelInformacionClinicaLayout.createSequentialGroup()
                            .addGap(185, 185, 185)
                            .addComponent(labelInformacionClinica))))
                .addContainerGap(269, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInformacionClinicaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonModClinica)
                .addGap(60, 60, 60))
        );
        panelInformacionClinicaLayout.setVerticalGroup(
            panelInformacionClinicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacionClinicaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelInformacionClinica)
                .addGap(51, 51, 51)
                .addGroup(panelInformacionClinicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNombre_DeLaClinica, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombreClinica))
                .addGap(28, 28, 28)
                .addGroup(panelInformacionClinicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRIFClinica)
                    .addComponent(labelRIF_DeLaClinica, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelInformacionClinicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelfClinica)
                    .addComponent(labelTelf_DeLaClinica, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelInformacionClinicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCiudad_DeLaClinca, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCiudadClinica))
                .addGap(30, 30, 30)
                .addGroup(panelInformacionClinicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelEstadoClinica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelEstado_DeLaClinica, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(panelInformacionClinicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDirClinica)
                    .addComponent(labelDir_DeLaClinica, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(botonModClinica)
                .addGap(41, 41, 41))
        );

        pestClinica.addTab("Información de la clínica", panelInformacionClinica);

        panelRegistrarAmbulatorio.setBackground(new java.awt.Color(255, 255, 255));
        panelRegistrarAmbulatorio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelNombre.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("Introduzca los datos del ambulatorio supeditado a la clínica");

        txtNombreAmbulatorio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNombreAmbulatorio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreAmbulatorioFocusLost(evt);
            }
        });
        txtNombreAmbulatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreAmbulatorioActionPerformed(evt);
            }
        });

        labelRIF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelRIF.setText("RIF:");

        txt8RIF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt8RIF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt8RIFFocusLost(evt);
            }
        });
        txt8RIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt8RIFActionPerformed(evt);
            }
        });

        labelPrivada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelPrivada.setText("J-");

        guion1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        guion1.setText("-");

        txt1RIF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt1RIF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt1RIFFocusLost(evt);
            }
        });
        txt1RIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1RIFActionPerformed(evt);
            }
        });

        txtTelf1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTelf1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelf1FocusLost(evt);
            }
        });
        txtTelf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelf1ActionPerformed(evt);
            }
        });

        labelTelf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTelf.setText("Teléfono:");

        guion2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        guion2.setText("-");

        txtTelf2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTelf2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelf2FocusLost(evt);
            }
        });
        txtTelf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelf2ActionPerformed(evt);
            }
        });

        labelDir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelDir.setText("Dirección:");

        labelCiudad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelCiudad.setText("Ciudad:");

        txtDir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirActionPerformed(evt);
            }
        });

        txtCiudad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCiudad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCiudadFocusLost(evt);
            }
        });
        txtCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCiudadActionPerformed(evt);
            }
        });

        labelEstado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelEstado.setText("Estado:");

        cboEstado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amazonas", "Anzoátegui", "Apure", "Aragua", "Barinas", "Bolívar", "Carabobo", "Cojedes", "Delta Amacuro", "Falcón", "Guárico", "Lara", "Mérida", "Miranda", "Monagas", "Nueva Esparta", "Portuguesa", "Sucre", "Táchira", "Trujillo", "Vargas", "Yaracuy", "Zulia" }));
        cboEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEstadoActionPerformed(evt);
            }
        });

        botonRegistrar.setBackground(new java.awt.Color(153, 204, 255));
        botonRegistrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        botonVaciar.setBackground(new java.awt.Color(255, 51, 51));
        botonVaciar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonVaciar.setText("Vaciar datos");
        botonVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVaciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRegistrarAmbulatorioLayout = new javax.swing.GroupLayout(panelRegistrarAmbulatorio);
        panelRegistrarAmbulatorio.setLayout(panelRegistrarAmbulatorioLayout);
        panelRegistrarAmbulatorioLayout.setHorizontalGroup(
            panelRegistrarAmbulatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrarAmbulatorioLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(panelRegistrarAmbulatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelRegistrarAmbulatorioLayout.createSequentialGroup()
                        .addComponent(labelDir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRegistrarAmbulatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelRegistrarAmbulatorioLayout.createSequentialGroup()
                            .addComponent(labelTelf)
                            .addGap(18, 18, 18)
                            .addComponent(txtTelf1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(guion2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTelf2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel6)
                        .addGroup(panelRegistrarAmbulatorioLayout.createSequentialGroup()
                            .addComponent(labelNombre)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNombreAmbulatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelRegistrarAmbulatorioLayout.createSequentialGroup()
                            .addComponent(labelRIF)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(labelPrivada)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt8RIF, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(guion1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt1RIF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelRegistrarAmbulatorioLayout.createSequentialGroup()
                            .addComponent(labelCiudad)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(labelEstado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistrarAmbulatorioLayout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addGroup(panelRegistrarAmbulatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistrarAmbulatorioLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistrarAmbulatorioLayout.createSequentialGroup()
                        .addComponent(botonVaciar)
                        .addGap(18, 18, 18)
                        .addComponent(botonRegistrar)
                        .addGap(33, 33, 33))))
        );
        panelRegistrarAmbulatorioLayout.setVerticalGroup(
            panelRegistrarAmbulatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrarAmbulatorioLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(panelRegistrarAmbulatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(txtNombreAmbulatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelRegistrarAmbulatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRIF)
                    .addComponent(txt8RIF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPrivada)
                    .addComponent(guion1)
                    .addComponent(txt1RIF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(30, 30, 30)
                .addGroup(panelRegistrarAmbulatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTelf)
                    .addComponent(txtTelf2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guion2))
                .addGap(36, 36, 36)
                .addGroup(panelRegistrarAmbulatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCiudad)
                    .addGroup(panelRegistrarAmbulatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelEstado)
                        .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(panelRegistrarAmbulatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDir)
                    .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(panelRegistrarAmbulatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonVaciar)
                    .addComponent(botonRegistrar))
                .addGap(40, 40, 40))
        );

        pestClinica.addTab("Registrar ambulatorio", panelRegistrarAmbulatorio);

        panelAsociarTaller.setBackground(new java.awt.Color(255, 255, 255));
        panelAsociarTaller.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelNombreTaller.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelNombreTaller.setText("Nombre:");

        solicitudTaller.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        solicitudTaller.setText("Introduzca los datos del taller que se desea asociar");

        txtNombreTaller.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNombreTaller.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreTallerFocusLost(evt);
            }
        });
        txtNombreTaller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreTallerActionPerformed(evt);
            }
        });

        labelRIFTaller.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelRIFTaller.setText("RIF:");

        txt8RIFTaller.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt8RIFTaller.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt8RIFTallerFocusLost(evt);
            }
        });
        txt8RIFTaller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt8RIFTallerActionPerformed(evt);
            }
        });

        labelPrivada1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelPrivada1.setText("J-");

        guion3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        guion3.setText("-");

        txt1RIFTaller.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt1RIFTaller.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt1RIFTallerFocusLost(evt);
            }
        });
        txt1RIFTaller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1RIFTallerActionPerformed(evt);
            }
        });

        txtTelf1_Taller.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTelf1_Taller.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelf1_TallerFocusLost(evt);
            }
        });
        txtTelf1_Taller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelf1_TallerActionPerformed(evt);
            }
        });

        labelTelf1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTelf1.setText("Teléfono:");

        guion4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        guion4.setText("-");

        txtTelf2_Taller.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTelf2_Taller.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelf2_TallerFocusLost(evt);
            }
        });
        txtTelf2_Taller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelf2_TallerActionPerformed(evt);
            }
        });

        labelDir_Taller.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelDir_Taller.setText("Dirección:");

        labelCiudad_Taller.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelCiudad_Taller.setText("Ciudad:");

        txtDir_Taller.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDir_Taller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDir_TallerActionPerformed(evt);
            }
        });

        txtCiudad_Taller.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCiudad_Taller.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCiudad_TallerFocusLost(evt);
            }
        });
        txtCiudad_Taller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCiudad_TallerActionPerformed(evt);
            }
        });

        labelEstado_Taller.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelEstado_Taller.setText("Estado:");

        cboEstado_Taller.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboEstado_Taller.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amazonas", "Anzoátegui", "Apure", "Aragua", "Barinas", "Bolívar", "Carabobo", "Cojedes", "Delta Amacuro", "Falcón", "Guárico", "Lara", "Mérida", "Miranda", "Monagas", "Nueva Esparta", "Portuguesa", "Sucre", "Táchira", "Trujillo", "Vargas", "Yaracuy", "Zulia" }));
        cboEstado_Taller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEstado_TallerActionPerformed(evt);
            }
        });

        botonAsociar.setBackground(new java.awt.Color(153, 204, 255));
        botonAsociar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonAsociar.setText("Asociar");
        botonAsociar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAsociarActionPerformed(evt);
            }
        });

        botonVaciar_Taller.setBackground(new java.awt.Color(255, 51, 51));
        botonVaciar_Taller.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonVaciar_Taller.setText("Vaciar datos");
        botonVaciar_Taller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVaciar_TallerActionPerformed(evt);
            }
        });

        txtNombreMecanico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreMecanicoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Mecánico:");

        jLabel3.setText("NOTA: La lista de mecánicos es opcional.");

        botonAgregarMecanico.setBackground(new java.awt.Color(51, 255, 51));
        botonAgregarMecanico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonAgregarMecanico.setText("Agregar mecanico a lista");
        botonAgregarMecanico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarMecanicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAsociarTallerLayout = new javax.swing.GroupLayout(panelAsociarTaller);
        panelAsociarTaller.setLayout(panelAsociarTallerLayout);
        panelAsociarTallerLayout.setHorizontalGroup(
            panelAsociarTallerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAsociarTallerLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelAsociarTallerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAsociarTallerLayout.createSequentialGroup()
                        .addGroup(panelAsociarTallerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAsociarTallerLayout.createSequentialGroup()
                                .addGap(327, 327, 327)
                                .addComponent(labelTelf1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelf1_Taller, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(guion4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelf2_Taller, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelAsociarTallerLayout.createSequentialGroup()
                                .addComponent(labelRIFTaller)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelPrivada1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt8RIFTaller, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(guion3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt1RIFTaller, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelAsociarTallerLayout.createSequentialGroup()
                                .addComponent(labelNombreTaller)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombreTaller, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAsociarTallerLayout.createSequentialGroup()
                        .addGroup(panelAsociarTallerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAsociarTallerLayout.createSequentialGroup()
                                .addGroup(panelAsociarTallerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAsociarTallerLayout.createSequentialGroup()
                                        .addComponent(labelCiudad_Taller)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCiudad_Taller, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(58, 58, 58)
                                        .addComponent(labelEstado_Taller)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cboEstado_Taller, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAsociarTallerLayout.createSequentialGroup()
                                        .addComponent(labelDir_Taller)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDir_Taller, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelAsociarTallerLayout.createSequentialGroup()
                                .addGroup(panelAsociarTallerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(panelAsociarTallerLayout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNombreMecanico, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(panelAsociarTallerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelAsociarTallerLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botonVaciar_Taller)
                                        .addGap(15, 15, 15)
                                        .addComponent(botonAsociar))
                                    .addGroup(panelAsociarTallerLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(botonAgregarMecanico)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(33, 33, 33))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAsociarTallerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(solicitudTaller)
                .addGap(137, 137, 137))
        );
        panelAsociarTallerLayout.setVerticalGroup(
            panelAsociarTallerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAsociarTallerLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(solicitudTaller, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelAsociarTallerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAsociarTallerLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(panelAsociarTallerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNombreTaller)
                            .addComponent(txtNombreTaller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(panelAsociarTallerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelRIFTaller)
                            .addComponent(txt8RIFTaller, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPrivada1)
                            .addComponent(guion3)
                            .addComponent(txt1RIFTaller, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelf1_Taller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTelf1)
                            .addComponent(txtTelf2_Taller, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guion4))
                        .addGap(27, 27, 27)
                        .addGroup(panelAsociarTallerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCiudad_Taller)
                            .addGroup(panelAsociarTallerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCiudad_Taller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelEstado_Taller)
                                .addComponent(cboEstado_Taller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(panelAsociarTallerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDir_Taller)
                            .addComponent(txtDir_Taller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(panelAsociarTallerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreMecanico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonAgregarMecanico))
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3)
                        .addGap(92, 92, 92))
                    .addGroup(panelAsociarTallerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelAsociarTallerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonVaciar_Taller)
                            .addComponent(botonAsociar))
                        .addGap(25, 25, 25))))
        );

        pestClinica.addTab("Asociar taller", panelAsociarTaller);

        panelClinica.add(pestClinica, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 810, 550));

        fondoClinica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Wallpaper.jpg"))); // NOI18N
        panelClinica.add(fondoClinica, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 660));

        panelesOp.addTab("Clínica", panelClinica);

        panelAmbulatorios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bhAmbulatorios.setBackground(new java.awt.Color(51, 51, 255));
        bhAmbulatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoHome.png"))); // NOI18N
        bhAmbulatorios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bhAmbulatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bhAmbulatoriosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bhAmbulatoriosMouseExited(evt);
            }
        });
        bhAmbulatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhAmbulatoriosActionPerformed(evt);
            }
        });
        panelAmbulatorios.add(bhAmbulatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(781, 20, 70, 60));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab1", jPanel5);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab2", jPanel8);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab3", jPanel9);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab4", jPanel10);

        panelAmbulatorios.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 800, 540));

        fondoAmbulatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Wallpaper.jpg"))); // NOI18N
        panelAmbulatorios.add(fondoAmbulatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 660));

        panelesOp.addTab("Ambulatorios", panelAmbulatorios);

        panelAmbulancias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bhAmbulancias.setBackground(new java.awt.Color(51, 51, 255));
        bhAmbulancias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoHome.png"))); // NOI18N
        bhAmbulancias.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bhAmbulancias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bhAmbulanciasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bhAmbulanciasMouseExited(evt);
            }
        });
        bhAmbulancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhAmbulanciasActionPerformed(evt);
            }
        });
        panelAmbulancias.add(bhAmbulancias, new org.netbeans.lib.awtextra.AbsoluteConstraints(781, 20, 70, 60));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("tab1", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("tab2", jPanel7);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("tab3", jPanel11);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("tab4", jPanel12);

        panelAmbulancias.add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 800, 540));

        fondoAmbulancias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Wallpaper.jpg"))); // NOI18N
        panelAmbulancias.add(fondoAmbulancias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 660));

        panelesOp.addTab("Ambulancias", panelAmbulancias);

        panelPacientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bhPacientes.setBackground(new java.awt.Color(51, 51, 255));
        bhPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoHome.png"))); // NOI18N
        bhPacientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bhPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bhPacientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bhPacientesMouseExited(evt);
            }
        });
        bhPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhPacientesActionPerformed(evt);
            }
        });
        panelPacientes.add(bhPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(781, 20, 70, 60));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("tab1", jPanel13);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("tab2", jPanel14);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("tab3", jPanel15);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("tab4", jPanel16);

        panelPacientes.add(jTabbedPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 800, 540));

        fondoPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Wallpaper.jpg"))); // NOI18N
        panelPacientes.add(fondoPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 660));

        panelesOp.addTab("Pacientes", panelPacientes);

        getContentPane().add(panelesOp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, -30, 890, 690));

        panelOpciones.setBackground(new java.awt.Color(255, 255, 255));

        botonAmbulancias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton ambulancias.jpg"))); // NOI18N
        botonAmbulancias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAmbulanciasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAmbulanciasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAmbulanciasMouseExited(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N

        botonAmbulatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton ambulatorio.jpg"))); // NOI18N
        botonAmbulatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAmbulatoriosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAmbulatoriosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAmbulatoriosMouseExited(evt);
            }
        });

        botonPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton pacientes.jpg"))); // NOI18N
        botonPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonPacientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonPacientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonPacientesMouseExited(evt);
            }
        });

        botonClinica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton clinica.jpg"))); // NOI18N
        botonClinica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonClinicaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonClinicaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonClinicaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelOpcionesLayout = new javax.swing.GroupLayout(panelOpciones);
        panelOpciones.setLayout(panelOpcionesLayout);
        panelOpcionesLayout.setHorizontalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonClinica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonAmbulatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpcionesLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(53, 53, 53))
            .addComponent(botonAmbulancias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(botonPacientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelOpcionesLayout.setVerticalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addComponent(botonClinica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(botonAmbulatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(botonAmbulancias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(botonPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(86, 86, 86))
        );

        getContentPane().add(panelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonClinicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonClinicaMouseClicked
        labelNombre_DeLaClinica.setText(controlClinica.getClinica().getNombre());
        labelRIF_DeLaClinica.setText(controlClinica.getClinica().getRIF());
        labelTelf_DeLaClinica.setText(controlClinica.getClinica().getTelefono());
        labelCiudad_DeLaClinca.setText(controlClinica.getClinica().getCiudad());
        labelEstado_DeLaClinica.setText(controlClinica.getClinica().getEstado());
        labelDir_DeLaClinica.setText(controlClinica.getClinica().getDireccion());
        panelesOp.setSelectedIndex(1); 
    }//GEN-LAST:event_botonClinicaMouseClicked

    private void botonClinicaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonClinicaMouseEntered
        // TODO add your handling code here:
        botonClinica.setBorder(borde);
    }//GEN-LAST:event_botonClinicaMouseEntered

    private void botonClinicaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonClinicaMouseExited
        // TODO add your handling code here:
        botonClinica.setBorder(null);
    }//GEN-LAST:event_botonClinicaMouseExited

    private void botonAmbulatoriosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAmbulatoriosMouseEntered
        // TODO add your handling code here:
        botonAmbulatorios.setBorder(borde);
    }//GEN-LAST:event_botonAmbulatoriosMouseEntered

    private void botonAmbulatoriosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAmbulatoriosMouseExited
        // TODO add your handling code here:
        botonAmbulatorios.setBorder(null);
    }//GEN-LAST:event_botonAmbulatoriosMouseExited

    private void botonAmbulanciasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAmbulanciasMouseEntered
        // TODO add your handling code here:
        botonAmbulancias.setBorder(borde);
    }//GEN-LAST:event_botonAmbulanciasMouseEntered

    private void botonAmbulanciasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAmbulanciasMouseExited
        // TODO add your handling code here:
        botonAmbulancias.setBorder(null);
    }//GEN-LAST:event_botonAmbulanciasMouseExited

    private void botonPacientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPacientesMouseEntered
        // TODO add your handling code here:
        botonPacientes.setBorder(borde);
    }//GEN-LAST:event_botonPacientesMouseEntered

    private void botonPacientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPacientesMouseExited
        // TODO add your handling code here:
        botonPacientes.setBorder(null);
    }//GEN-LAST:event_botonPacientesMouseExited

    private void botonAmbulatoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAmbulatoriosMouseClicked
        //panelesOp.setVisible(true);
        panelesOp.setSelectedIndex(2);
    }//GEN-LAST:event_botonAmbulatoriosMouseClicked

    private void botonAmbulanciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAmbulanciasMouseClicked
        //panelesOp.setVisible(true);
        panelesOp.setSelectedIndex(3);
    }//GEN-LAST:event_botonAmbulanciasMouseClicked

    private void botonPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPacientesMouseClicked
        //panelesOp.setVisible(true);
        panelesOp.setSelectedIndex(4);
    }//GEN-LAST:event_botonPacientesMouseClicked

    private void bhClinicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhClinicaActionPerformed
        // TODO add your handling code here:
        panelesOp.setSelectedIndex(0);
    }//GEN-LAST:event_bhClinicaActionPerformed

    private void bhAmbulatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhAmbulatoriosActionPerformed
        // TODO add your handling code here:
        panelesOp.setSelectedIndex(0);
    }//GEN-LAST:event_bhAmbulatoriosActionPerformed

    private void bhAmbulanciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhAmbulanciasActionPerformed
        // TODO add your handling code here:
        panelesOp.setSelectedIndex(0);
    }//GEN-LAST:event_bhAmbulanciasActionPerformed

    private void bhPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhPacientesActionPerformed
        // TODO add your handling code here:
        panelesOp.setSelectedIndex(0);
    }//GEN-LAST:event_bhPacientesActionPerformed

    private void bhClinicaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhClinicaMouseEntered
        // TODO add your handling code here:
        bhClinica.setBorder(bordeAmarillo);
    }//GEN-LAST:event_bhClinicaMouseEntered

    private void bhAmbulatoriosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhAmbulatoriosMouseEntered
        // TODO add your handling code here:
        bhAmbulatorios.setBorder(bordeAmarillo);
    }//GEN-LAST:event_bhAmbulatoriosMouseEntered

    private void bhAmbulanciasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhAmbulanciasMouseEntered
        // TODO add your handling code here:
        bhAmbulancias.setBorder(bordeAmarillo);
    }//GEN-LAST:event_bhAmbulanciasMouseEntered

    private void bhPacientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhPacientesMouseEntered
        // TODO add your handling code here:
        bhPacientes.setBorder(bordeAmarillo);
    }//GEN-LAST:event_bhPacientesMouseEntered

    private void bhClinicaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhClinicaMouseExited
        // TODO add your handling code here:
        bhClinica.setBorder(null);
    }//GEN-LAST:event_bhClinicaMouseExited

    private void bhAmbulatoriosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhAmbulatoriosMouseExited
        // TODO add your handling code here:
        bhAmbulatorios.setBorder(null);
    }//GEN-LAST:event_bhAmbulatoriosMouseExited

    private void bhAmbulanciasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhAmbulanciasMouseExited
        // TODO add your handling code here:
        bhAmbulancias.setBorder(null);
    }//GEN-LAST:event_bhAmbulanciasMouseExited

    private void bhPacientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhPacientesMouseExited
        // TODO add your handling code here:
        bhPacientes.setBorder(null);
    }//GEN-LAST:event_bhPacientesMouseExited

    private void cboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEstadoActionPerformed

    private void txtCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCiudadActionPerformed

    private void txtDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirActionPerformed

    private void txtTelf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelf2ActionPerformed

    private void txtTelf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelf1ActionPerformed

    private void txt1RIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1RIFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1RIFActionPerformed

    private void txt8RIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt8RIFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt8RIFActionPerformed

    private void txtNombreAmbulatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreAmbulatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAmbulatorioActionPerformed

    private void txtTelf1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelf1FocusLost
        // TODO add your handling code here:
        if(cRegistro.validarTelf(txtTelf1,4)==false) txtTelf1.setText(null);
    }//GEN-LAST:event_txtTelf1FocusLost

    private void txtTelf2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelf2FocusLost
        // TODO add your handling code here:
        if(cRegistro.validarTelf(txtTelf2,7)==false) txtTelf2.setText(null);
    }//GEN-LAST:event_txtTelf2FocusLost

    private void txtCiudadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCiudadFocusLost
if(cRegistro.validarNombre(txtCiudad)==false) txtCiudad.setText(null);
    }//GEN-LAST:event_txtCiudadFocusLost

    private void botonVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVaciarActionPerformed
        cRegistro.vaciarDatosEntidad(txtNombreAmbulatorio,txt8RIF,txt1RIF,txtTelf1,txtTelf2,txtCiudad,txtDir,cboEstado);
    }//GEN-LAST:event_botonVaciarActionPerformed

    private void txt8RIFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt8RIFFocusLost
        // TODO add your handling code here:
        if(cRegistro.validarRIF(txt8RIF,8)==false) txt8RIF.setText(null);
    }//GEN-LAST:event_txt8RIFFocusLost

    private void txt1RIFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt1RIFFocusLost
        // TODO add your handling code here:
        if(cRegistro.validarRIF(txt1RIF,1)==false) txt1RIF.setText(null);
    }//GEN-LAST:event_txt1RIFFocusLost

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        if(cRegistro.camposVaciosEntidad(txtNombreAmbulatorio,txt8RIF,txt1RIF,txtTelf1,txtTelf2,txtCiudad,txtDir)==false){
            String RIF = cRegistro.construirRIF(txt8RIF,txt1RIF);
            String telf = cRegistro.construirTelf(txtTelf1,txtTelf2);
            if(controlSistema.seEncuentraRegistrada_RIF(RIF,false)==false && controlSistema.seEncuentraRegistrada_Telf(telf)==false){
                if(cRegistro.confirmar()==true){
                    controlClinica.crearAmbulatorio(controlClinica.getClinica(), txtNombreAmbulatorio.getText(), RIF,telf,txtCiudad.getText(),txtDir.getText(),cboEstado.getSelectedItem().toString());
                    cRegistro.vaciarDatosEntidad(txtNombreAmbulatorio, txt8RIF, txt1RIF, txtTelf1, txtTelf2, txtCiudad, txtDir, cboEstado);
                }   
            }
        }
    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void txtNombreAmbulatorioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreAmbulatorioFocusLost
        // TODO add your handling code here:
        if(cRegistro.validarNombre(txtNombreAmbulatorio)==false) txtNombreAmbulatorio.setText(null);
    }//GEN-LAST:event_txtNombreAmbulatorioFocusLost

    private void botonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarSesionActionPerformed
        // TODO add your handling code here:
        iniciarSesion.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonCerrarSesionActionPerformed

    private void botonVaciar_TallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVaciar_TallerActionPerformed
        cRegistro.vaciarDatosEntidad(txtNombreTaller,txt8RIFTaller,txt1RIFTaller,txtTelf1_Taller,txtTelf2_Taller,txtCiudad_Taller,txtDir_Taller,cboEstado_Taller);
        txtNombreMecanico.setText(null);
        listaMecanicos.clear();
        listaMecanicos = new ArrayList<>();
    }//GEN-LAST:event_botonVaciar_TallerActionPerformed

    private void botonAsociarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAsociarActionPerformed
        if(cRegistro.camposVaciosEntidad(txtNombreTaller,txt8RIFTaller,txt1RIFTaller,txtTelf1_Taller,txtTelf2_Taller,txtCiudad_Taller,txtDir_Taller)==false){
            String RIF = cRegistro.construirRIF(txt8RIFTaller,txt1RIFTaller);
            String telf = cRegistro.construirTelf(txtTelf1_Taller,txtTelf2_Taller);
            if(controlSistema.seEncuentraRegistrada_RIF(RIF,false)==false && controlSistema.seEncuentraRegistrada_Telf(telf)==false){
                if(cRegistro.confirmar()==true){
                    controlClinica.crearTaller(controlClinica.getClinica(),txtNombreTaller.getText(),RIF,telf, txtCiudad_Taller.getText(), txtDir_Taller.getText(), cboEstado_Taller.getSelectedItem().toString(),listaMecanicos);
                    cRegistro.vaciarDatosEntidad(txtNombreTaller, txt8RIFTaller, txt1RIFTaller, txtTelf1_Taller, txtTelf2_Taller, txtCiudad_Taller, txtDir_Taller, cboEstado_Taller);
                    txtNombreMecanico.setText(null);
                    listaMecanicos.clear();
                    listaMecanicos = new ArrayList<>();
                }
            }
        }
    }//GEN-LAST:event_botonAsociarActionPerformed

    private void cboEstado_TallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEstado_TallerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEstado_TallerActionPerformed

    private void txtCiudad_TallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCiudad_TallerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCiudad_TallerActionPerformed

    private void txtCiudad_TallerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCiudad_TallerFocusLost
        if(cRegistro.validarNombre(txtCiudad_Taller)==false) txtCiudad_Taller.setText(null);
    }//GEN-LAST:event_txtCiudad_TallerFocusLost

    private void txtDir_TallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDir_TallerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDir_TallerActionPerformed

    private void txtTelf2_TallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelf2_TallerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelf2_TallerActionPerformed

    private void txtTelf2_TallerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelf2_TallerFocusLost
        if(cRegistro.validarTelf(txtTelf2_Taller,7)==false) txtTelf2_Taller.setText(null);
    }//GEN-LAST:event_txtTelf2_TallerFocusLost

    private void txtTelf1_TallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelf1_TallerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelf1_TallerActionPerformed

    private void txtTelf1_TallerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelf1_TallerFocusLost
        if(cRegistro.validarTelf(txtTelf1_Taller,4)==false) txtTelf1_Taller.setText(null);
    }//GEN-LAST:event_txtTelf1_TallerFocusLost

    private void txt1RIFTallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1RIFTallerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1RIFTallerActionPerformed

    private void txt1RIFTallerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt1RIFTallerFocusLost
        // TODO add your handling code here:
        if(cRegistro.validarRIF(txt1RIFTaller,1)==false) txt1RIFTaller.setText(null);
    }//GEN-LAST:event_txt1RIFTallerFocusLost

    private void txt8RIFTallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt8RIFTallerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt8RIFTallerActionPerformed

    private void txt8RIFTallerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt8RIFTallerFocusLost
        // TODO add your handling code here:
        if(cRegistro.validarRIF(txt8RIFTaller,8)==false) txt8RIFTaller.setText(null);
    }//GEN-LAST:event_txt8RIFTallerFocusLost

    private void txtNombreTallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreTallerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreTallerActionPerformed

    private void txtNombreTallerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreTallerFocusLost
        if(cRegistro.validarNombre(txtNombreTaller)==false) txtNombreTaller.setText(null);
    }//GEN-LAST:event_txtNombreTallerFocusLost

    private void txtNombreMecanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreMecanicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMecanicoActionPerformed

    private void botonAgregarMecanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarMecanicoActionPerformed
        if(txtNombreMecanico.getText().isEmpty()) JOptionPane.showInputDialog(null,"Este campo está vacío","Error", JOptionPane.ERROR_MESSAGE);
        else{
            if(cRegistro.validarNombre(txtNombreMecanico)) listaMecanicos.add(txtNombreMecanico.getText());
        }
        txtNombreMecanico.setText(null);
    }//GEN-LAST:event_botonAgregarMecanicoActionPerformed

    private void botonModClinicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModClinicaActionPerformed
        setVisible(false);
        ModificarEntidad modClinica = new ModificarEntidad(this,controlClinica.getClinica());
        modClinica.setVisible(true);
    }//GEN-LAST:event_botonModClinicaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenúPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenúPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenúPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenúPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenúPrincipal().setVisible(true);
            }
        });
    }

    //GETTERS PARA ACTUALIZAR LA PESTAÑAS MOSTRAR INFORMACIÓN
    
    //LABELS DE LA CLINICA
    public JLabel getLabelCiudad_DeLaClinca() {
        return labelCiudad_DeLaClinca;
    }

    public JLabel getLabelDir_DeLaClinica() {
        return labelDir_DeLaClinica;
    }

    public JLabel getLabelEstado_DeLaClinica() {
        return labelEstado_DeLaClinica;
    }

    public JLabel getLabelNombre_DeLaClinica() {
        return labelNombre_DeLaClinica;
    }

    public JLabel getLabelRIF_DeLaClinica() {
        return labelRIF_DeLaClinica;
    }

    public JLabel getLabelTelf_DeLaClinica() {
        return labelTelf_DeLaClinica;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bhAmbulancias;
    private javax.swing.JButton bhAmbulatorios;
    private javax.swing.JButton bhClinica;
    private javax.swing.JButton bhPacientes;
    private javax.swing.JButton botonAgregarMecanico;
    private javax.swing.JLabel botonAmbulancias;
    private javax.swing.JLabel botonAmbulatorios;
    private javax.swing.JButton botonAsociar;
    private javax.swing.JButton botonCerrarSesion;
    private javax.swing.JLabel botonClinica;
    private javax.swing.JButton botonModClinica;
    private javax.swing.JLabel botonPacientes;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JButton botonVaciar;
    private javax.swing.JButton botonVaciar_Taller;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JComboBox<String> cboEstado_Taller;
    private javax.swing.JLabel fondoAmbulancias;
    private javax.swing.JLabel fondoAmbulatorios;
    private javax.swing.JLabel fondoClinica;
    private javax.swing.JLabel fondoHome;
    private javax.swing.JLabel fondoPacientes;
    private javax.swing.JLabel guion1;
    private javax.swing.JLabel guion2;
    private javax.swing.JLabel guion3;
    private javax.swing.JLabel guion4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JLabel labelCiudad;
    private javax.swing.JLabel labelCiudadClinica;
    private javax.swing.JLabel labelCiudad_DeLaClinca;
    private javax.swing.JLabel labelCiudad_Taller;
    private javax.swing.JLabel labelDir;
    private javax.swing.JLabel labelDirClinica;
    private javax.swing.JLabel labelDir_DeLaClinica;
    private javax.swing.JLabel labelDir_Taller;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelEstadoClinica;
    private javax.swing.JLabel labelEstado_DeLaClinica;
    private javax.swing.JLabel labelEstado_Taller;
    private javax.swing.JLabel labelInformacionClinica;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombreClinica;
    private javax.swing.JLabel labelNombreTaller;
    private javax.swing.JLabel labelNombre_DeLaClinica;
    private javax.swing.JLabel labelPrivada;
    private javax.swing.JLabel labelPrivada1;
    private javax.swing.JLabel labelRIF;
    private javax.swing.JLabel labelRIFClinica;
    private javax.swing.JLabel labelRIFTaller;
    private javax.swing.JLabel labelRIF_DeLaClinica;
    private javax.swing.JLabel labelTelf;
    private javax.swing.JLabel labelTelf1;
    private javax.swing.JLabel labelTelfClinica;
    private javax.swing.JLabel labelTelf_DeLaClinica;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panelAmbulancias;
    private javax.swing.JPanel panelAmbulatorios;
    private javax.swing.JPanel panelAsociarTaller;
    private javax.swing.JPanel panelClinica;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelInformacionClinica;
    private javax.swing.JPanel panelMostrarAmbulatorios;
    private javax.swing.JPanel panelOpciones;
    private javax.swing.JPanel panelPacientes;
    private javax.swing.JPanel panelRegistrarAmbulatorio;
    private javax.swing.JTabbedPane panelesOp;
    private javax.swing.JTabbedPane pestClinica;
    private javax.swing.JLabel solicitudTaller;
    private javax.swing.JTextField txt1RIF;
    private javax.swing.JTextField txt1RIFTaller;
    private javax.swing.JTextField txt8RIF;
    private javax.swing.JTextField txt8RIFTaller;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCiudad_Taller;
    private javax.swing.JTextField txtDir;
    private javax.swing.JTextField txtDir_Taller;
    private javax.swing.JTextField txtNombreAmbulatorio;
    private javax.swing.JTextField txtNombreMecanico;
    private javax.swing.JTextField txtNombreTaller;
    private javax.swing.JTextField txtTelf1;
    private javax.swing.JTextField txtTelf1_Taller;
    private javax.swing.JTextField txtTelf2;
    private javax.swing.JTextField txtTelf2_Taller;
    // End of variables declaration//GEN-END:variables
}
