/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.*;
import Controller.*;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JTable;

public class ModificarPaciente extends javax.swing.JFrame {
    Paciente paciente;
    CPaciente pac;
    CVentana controlVentana = new CVentana();
    CRegistro controlRegistro = new CRegistro();
    CSistema controlSistema;
    MenúPrincipal ventanaAnterior;
    private JButton btnDetalles;
    private JButton jBtnEliminar;
    private JButton jbtnModificar;
    private JTable jTablePacientes;

    public ModificarPaciente() {
        initComponents();
    }
    
    public ModificarPaciente(MenúPrincipal ventanaAnterior,Paciente paciente,CSistema controlSistema,JButton btnDetalles,JButton jBtnEliminar,JButton jbtnModificar, JTable jTablePacientes) {
        initComponents();
        this.paciente = paciente;
        this.ventanaAnterior = ventanaAnterior;
        this.controlSistema=controlSistema;
        this.btnDetalles=btnDetalles;
        this.jBtnEliminar=jBtnEliminar;
        this.jbtnModificar=jbtnModificar;
        this.jTablePacientes=jTablePacientes;
       
        
        controlVentana.iniciarVentana(this, "src/imagenes/logo(1).png");    
        controlVentana.entradasModificar_Paciente(paciente, cboCI_Paciente,txtCedula, txtNombre, txtCorreo, txtTelf1, txtTelf2, DateFecha, boxGenero);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMod = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelNombreEntidad = new javax.swing.JLabel();
        labelTelfEntidad = new javax.swing.JLabel();
        labelCiudadEntidad = new javax.swing.JLabel();
        labelEstadoEntidad = new javax.swing.JLabel();
        labelDirEntidad = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTelf1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelf2 = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        boxGenero = new javax.swing.JComboBox<>();
        botonGuardarCambios = new javax.swing.JButton();
        botonReestablecer = new javax.swing.JButton();
        radioModNombre = new javax.swing.JRadioButton();
        radioModTelf = new javax.swing.JRadioButton();
        radioModGenero = new javax.swing.JRadioButton();
        radioModFecha = new javax.swing.JRadioButton();
        botonSalir = new javax.swing.JButton();
        labelCiudadEntidad1 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        radioModCorreo = new javax.swing.JRadioButton();
        DateFecha = new com.toedter.calendar.JDateChooser();
        cboCI_Paciente = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMod.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Seleccione el dato a modificar");

        labelNombreEntidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelNombreEntidad.setText("Nombre:");

        labelTelfEntidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTelfEntidad.setText("Teléfono:");

        labelCiudadEntidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelCiudadEntidad.setText("Cedula :");

        labelEstadoEntidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelEstadoEntidad.setText("Genero : ");

        labelDirEntidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelDirEntidad.setText("Nacimiento :");

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("-");

        txtTelf1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTelf1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelf1FocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("-");

        txtTelf2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTelf2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelf2FocusLost(evt);
            }
        });
        txtTelf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelf2ActionPerformed(evt);
            }
        });

        txtCedula.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCedulaFocusLost(evt);
            }
        });
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });

        boxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        botonGuardarCambios.setBackground(new java.awt.Color(153, 204, 255));
        botonGuardarCambios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonGuardarCambios.setText("Guardar cambios");
        botonGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarCambiosActionPerformed(evt);
            }
        });

        botonReestablecer.setBackground(new java.awt.Color(51, 255, 0));
        botonReestablecer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonReestablecer.setText("Reestablecer");
        botonReestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReestablecerActionPerformed(evt);
            }
        });

        radioModNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radioModNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioModNombreMouseClicked(evt);
            }
        });

        radioModTelf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radioModTelf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioModTelfMouseClicked(evt);
            }
        });
        radioModTelf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioModTelfActionPerformed(evt);
            }
        });

        radioModGenero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radioModGenero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioModGeneroMouseClicked(evt);
            }
        });

        radioModFecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radioModFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioModFechaMouseClicked(evt);
            }
        });

        botonSalir.setBackground(new java.awt.Color(255, 0, 0));
        botonSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        labelCiudadEntidad1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelCiudadEntidad1.setText("Correo :");

        txtCorreo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoFocusLost(evt);
            }
        });
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        radioModCorreo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radioModCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioModCorreoMouseClicked(evt);
            }
        });
        radioModCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioModCorreoActionPerformed(evt);
            }
        });

        cboCI_Paciente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboCI_Paciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "V", "E" }));
        cboCI_Paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCI_PacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelModLayout = new javax.swing.GroupLayout(panelMod);
        panelMod.setLayout(panelModLayout);
        panelModLayout.setHorizontalGroup(
            panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonReestablecer, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonGuardarCambios)
                .addGap(48, 48, 48))
            .addGroup(panelModLayout.createSequentialGroup()
                .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelModLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addGroup(panelModLayout.createSequentialGroup()
                                    .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelModLayout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(labelCiudadEntidad1)
                                                .addGroup(panelModLayout.createSequentialGroup()
                                                    .addComponent(labelNombreEntidad)
                                                    .addGap(130, 130, 130)
                                                    .addComponent(jLabel3))))
                                        .addGroup(panelModLayout.createSequentialGroup()
                                            .addComponent(labelEstadoEntidad)
                                            .addGap(22, 22, 22)
                                            .addComponent(boxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(radioModGenero)))
                                    .addGap(239, 239, 239)))
                            .addGroup(panelModLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(labelCiudadEntidad)
                                .addGap(36, 36, 36)
                                .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelModLayout.createSequentialGroup()
                                        .addComponent(cboCI_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelModLayout.createSequentialGroup()
                                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radioModCorreo))
                                    .addGroup(panelModLayout.createSequentialGroup()
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radioModNombre))))))
                    .addGroup(panelModLayout.createSequentialGroup()
                        .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelModLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(labelTelfEntidad)
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelDirEntidad)
                                .addGap(18, 18, 18)))
                        .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelModLayout.createSequentialGroup()
                                .addComponent(txtTelf1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelf2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioModTelf))
                            .addComponent(DateFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(radioModFecha)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(botonSalir)
                .addGap(25, 25, 25))
        );
        panelModLayout.setVerticalGroup(
            panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModLayout.createSequentialGroup()
                .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelModLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1))
                    .addGroup(panelModLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonSalir)))
                .addGap(29, 29, 29)
                .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboCI_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelCiudadEntidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelNombreEntidad))
                    .addComponent(radioModNombre))
                .addGap(20, 20, 20)
                .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(radioModCorreo)
                    .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelCiudadEntidad1)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioModTelf)
                    .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelTelfEntidad)
                        .addComponent(txtTelf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(txtTelf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(radioModFecha, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DateFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDirEntidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioModGenero)
                    .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelEstadoEntidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72)
                .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardarCambios)
                    .addComponent(botonReestablecer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        getContentPane().add(panelMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        dispose();
        ventanaAnterior.setVisible(true);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void radioModFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioModFechaMouseClicked
        if(radioModFecha.isSelected()){
            DateFecha.setEnabled(true);
            DateFecha.setDate(null);
        }
        else {
            DateFecha.setEnabled(false);
            ZoneId defaultZoneId = ZoneId.systemDefault();

            DateFecha.setDate(Date.from(paciente.getNacimiento().atStartOfDay(defaultZoneId).toInstant()));
        }
    }//GEN-LAST:event_radioModFechaMouseClicked

    private void radioModGeneroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioModGeneroMouseClicked
        if(radioModGenero.isSelected()) {
            
            if (paciente.getGenero()=='M'){
                boxGenero.setSelectedIndex(0);
            }else if(paciente.getGenero()=='F'){
                boxGenero.setSelectedIndex(1);

            }
            boxGenero.setEnabled(true);
            
        }else{
                
                if (paciente.getGenero()=='M'){
                boxGenero.setSelectedIndex(0);
            }else if(paciente.getGenero()=='F'){
                boxGenero.setSelectedIndex(1);

            }
            boxGenero.setEnabled(false);
        }
    }//GEN-LAST:event_radioModGeneroMouseClicked

    private void radioModTelfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioModTelfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioModTelfActionPerformed

    private void radioModTelfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioModTelfMouseClicked
        if(radioModTelf.isSelected()){
            txtTelf1.setEnabled(true);
            txtTelf2.setEnabled(true);
            txtTelf1.setText(null);
            txtTelf2.setText(null);
        }
        else{
            txtTelf1.setEnabled(false);
            txtTelf2.setEnabled(false);
            txtTelf1.setText(paciente.getTelefono().substring(0,4));
            txtTelf2.setText(paciente.getTelefono().substring(5));
        }
    }//GEN-LAST:event_radioModTelfMouseClicked

    private void radioModNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioModNombreMouseClicked
        if(radioModNombre.isSelected()){
            txtNombre.setEnabled(true);
            txtNombre.setText(null);
        }
        else{
            txtNombre.setEnabled(false);
            txtNombre.setText(paciente.getNombre());
        }
    }//GEN-LAST:event_radioModNombreMouseClicked

    private void botonReestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReestablecerActionPerformed
        controlRegistro.construirTelf(txtTelf1, txtTelf2);
        controlVentana.entradasModificar_Paciente(paciente, cboCI_Paciente,txtCedula, txtNombre, txtCorreo, txtTelf1, txtTelf2, DateFecha, boxGenero);
        controlVentana.seleccionarBotonesRadio_Paciente(false, radioModNombre, radioModCorreo, radioModTelf, radioModFecha, radioModGenero);
    }//GEN-LAST:event_botonReestablecerActionPerformed

    private void botonGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarCambiosActionPerformed
        boolean validaciones = controlRegistro.validarTelf(txtTelf1,4) && controlRegistro.validarTelf(txtTelf2,7) && controlRegistro.validarCI(txtCedula.getText());
        if(validaciones && controlRegistro.camposVaciosPaciente(txtCedula, txtNombre, txtCorreo, txtTelf1, txtTelf2, DateFecha, boxGenero)==false){
            boolean modTelf=false,continuar=true;
            String telf = controlRegistro.construirTelf(txtTelf1, txtTelf2);
            if(!telf.equals(paciente.getTelefono())) modTelf=true;

            if(modTelf==true && controlSistema.seEncuentraRegistrada_Telf(telf)) continuar=false;

            if(continuar){
                if(controlRegistro.confirmar()){
                    dispose();
                    
                    String cedula = controlRegistro.construirCedula(cboCI_Paciente, txtCedula);
                    
                    controlRegistro.actualizarPaciente(paciente, cedula, txtNombre, txtCorreo, telf, DateFecha, boxGenero);
                    ventanaAnterior.pac.mostrarPacientes(jTablePacientes, controlSistema.getListaPacientes(),btnDetalles,jBtnEliminar,jbtnModificar);
                    ventanaAnterior.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_botonGuardarCambiosActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtCedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCedulaFocusLost
        if(!controlRegistro.validarCI(txtCedula.getText())) txtCedula.setText(null);
    }//GEN-LAST:event_txtCedulaFocusLost

    private void txtTelf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelf2ActionPerformed

    private void txtTelf2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelf2FocusLost
        if(!controlRegistro.validarTelf(txtTelf2,7)) txtTelf2.setText(null);
    }//GEN-LAST:event_txtTelf2FocusLost

    private void txtTelf1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelf1FocusLost
        if(!controlRegistro.validarTelf(txtTelf1,4)) txtTelf1.setText(null);
    }//GEN-LAST:event_txtTelf1FocusLost

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoFocusLost

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void radioModCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioModCorreoMouseClicked
        // TODO add your handling code here:
        if(radioModCorreo.isSelected()){
            
            txtCorreo.setEnabled(true);
            txtCorreo.setText(null);
            
        }else{
            
            txtCorreo.setEnabled(false);
            txtCorreo.setText(paciente.getCorreo());
         
        }
    }//GEN-LAST:event_radioModCorreoMouseClicked

    private void radioModCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioModCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioModCorreoActionPerformed

    private void cboCI_PacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCI_PacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCI_PacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarPaciente().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateFecha;
    private javax.swing.JButton botonGuardarCambios;
    private javax.swing.JButton botonReestablecer;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox<String> boxGenero;
    private javax.swing.JComboBox<String> cboCI_Paciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelCiudadEntidad;
    private javax.swing.JLabel labelCiudadEntidad1;
    private javax.swing.JLabel labelDirEntidad;
    private javax.swing.JLabel labelEstadoEntidad;
    private javax.swing.JLabel labelNombreEntidad;
    private javax.swing.JLabel labelTelfEntidad;
    private javax.swing.JPanel panelMod;
    private javax.swing.JRadioButton radioModCorreo;
    private javax.swing.JRadioButton radioModFecha;
    private javax.swing.JRadioButton radioModGenero;
    private javax.swing.JRadioButton radioModNombre;
    private javax.swing.JRadioButton radioModTelf;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelf1;
    private javax.swing.JTextField txtTelf2;
    // End of variables declaration//GEN-END:variables
}
