/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.*;
import Controller.*;

public class ModificarEntidad extends javax.swing.JFrame {
    Entidad entidad;
    CVentana controlVentana = new CVentana();
    CRegistro controlRegistro = new CRegistro();
    CClinica controlClinica;
    MenúPrincipal ventanaAnterior;

    public ModificarEntidad() {
        initComponents();
    }
    
    public ModificarEntidad(MenúPrincipal ventanaAnterior,Entidad entidad) {
        initComponents();
        this.entidad = entidad;
        this.ventanaAnterior = ventanaAnterior;
        controlVentana.iniciarVentana(this, "src/imagenes/logo(1).png");    
        controlVentana.entradasModificar_Entidad(entidad,txtNombreEntidad, txt8RIFEntidad, txt1RIFEntidad, txtTelf1Entidad, txtTelf2Entidad, txtCiudadEntidad, cboEstadoEntidad, txtDirEntidad);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMod = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelNombreEntidad = new javax.swing.JLabel();
        labelRIFEntidad = new javax.swing.JLabel();
        labelTelfEntidad = new javax.swing.JLabel();
        labelCiudadEntidad = new javax.swing.JLabel();
        labelEstadoEntidad = new javax.swing.JLabel();
        labelDirEntidad = new javax.swing.JLabel();
        txtNombreEntidad = new javax.swing.JTextField();
        txt8RIFEntidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt1RIFEntidad = new javax.swing.JTextField();
        txtTelf1Entidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelf2Entidad = new javax.swing.JTextField();
        txtCiudadEntidad = new javax.swing.JTextField();
        cboEstadoEntidad = new javax.swing.JComboBox<>();
        txtDirEntidad = new javax.swing.JTextField();
        botonGuardarCambios = new javax.swing.JButton();
        botonReestablecer = new javax.swing.JButton();
        radioModNombre = new javax.swing.JRadioButton();
        radioModRIF = new javax.swing.JRadioButton();
        radioModTelf = new javax.swing.JRadioButton();
        radioModCiudad = new javax.swing.JRadioButton();
        radioModEstado = new javax.swing.JRadioButton();
        radioModDir = new javax.swing.JRadioButton();
        botonSalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMod.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Seleccione el dato a modificar");

        labelNombreEntidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelNombreEntidad.setText("Nombre:");

        labelRIFEntidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelRIFEntidad.setText("RIF:");

        labelTelfEntidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTelfEntidad.setText("Teléfono:");

        labelCiudadEntidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelCiudadEntidad.setText("Ciudad:");

        labelEstadoEntidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelEstadoEntidad.setText("Estado:");

        labelDirEntidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelDirEntidad.setText("Dirección:");

        txtNombreEntidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNombreEntidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEntidadActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("J-");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("-");

        txt1RIFEntidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("-");

        txtTelf2Entidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTelf2Entidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelf2EntidadActionPerformed(evt);
            }
        });

        txtCiudadEntidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cboEstadoEntidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amazonas", "Anzoátegui", "Apure", "Aragua", "Barinas", "Bolívar", "Carabobo", "Cojedes", "Delta Amacuro", "Falcón", "Guárico", "Lara", "Mérida", "Miranda", "Monagas", "Nueva Esparta", "Portuguesa", "Sucre", "Táchira", "Trujillo", "Vargas", "Yaracuy", "Zulia" }));

        botonGuardarCambios.setBackground(new java.awt.Color(153, 204, 255));
        botonGuardarCambios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonGuardarCambios.setText("Guardar cambios");
        botonGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarCambiosActionPerformed(evt);
            }
        });

        botonReestablecer.setBackground(new java.awt.Color(51, 255, 0));
        botonReestablecer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonReestablecer.setText("Reestablecer");
        botonReestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReestablecerActionPerformed(evt);
            }
        });

        radioModNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radioModNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioModNombreMouseClicked(evt);
            }
        });
        radioModNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioModNombreActionPerformed(evt);
            }
        });

        radioModRIF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radioModRIF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioModRIFMouseClicked(evt);
            }
        });
        radioModRIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioModRIFActionPerformed(evt);
            }
        });

        radioModTelf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radioModTelf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioModTelfMouseClicked(evt);
            }
        });
        radioModTelf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioModTelfActionPerformed(evt);
            }
        });

        radioModCiudad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radioModCiudad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioModCiudadMouseClicked(evt);
            }
        });

        radioModEstado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radioModEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioModEstadoMouseClicked(evt);
            }
        });

        radioModDir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radioModDir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioModDirMouseClicked(evt);
            }
        });

        botonSalir.setBackground(new java.awt.Color(255, 0, 0));
        botonSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelModLayout = new javax.swing.GroupLayout(panelMod);
        panelMod.setLayout(panelModLayout);
        panelModLayout.setHorizontalGroup(
            panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelModLayout.createSequentialGroup()
                        .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelModLayout.createSequentialGroup()
                                .addComponent(labelCiudadEntidad)
                                .addGap(18, 18, 18)
                                .addComponent(txtCiudadEntidad))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelModLayout.createSequentialGroup()
                                .addComponent(labelTelfEntidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelf1Entidad, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelf2Entidad, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioModCiudad)
                            .addComponent(radioModTelf))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelModLayout.createSequentialGroup()
                        .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelModLayout.createSequentialGroup()
                                    .addComponent(labelNombreEntidad)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtNombreEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelModLayout.createSequentialGroup()
                                    .addComponent(labelEstadoEntidad)
                                    .addGap(18, 18, 18)
                                    .addComponent(cboEstadoEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(radioModEstado))
                                .addGroup(panelModLayout.createSequentialGroup()
                                    .addComponent(labelDirEntidad)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtDirEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelModLayout.createSequentialGroup()
                                    .addComponent(labelRIFEntidad)
                                    .addGap(24, 24, 24)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt8RIFEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt1RIFEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(radioModRIF))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioModNombre)
                            .addComponent(radioModDir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(botonSalir)
                        .addGap(25, 25, 25))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonReestablecer, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonGuardarCambios)
                .addGap(48, 48, 48))
        );
        panelModLayout.setVerticalGroup(
            panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModLayout.createSequentialGroup()
                .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelModLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1))
                    .addGroup(panelModLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonSalir)))
                .addGap(18, 18, 18)
                .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioModNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNombreEntidad)
                        .addComponent(txtNombreEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioModRIF)
                    .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelRIFEntidad)
                        .addComponent(txt8RIFEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(txt1RIFEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioModTelf)
                    .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelTelfEntidad)
                        .addComponent(txtTelf1Entidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(txtTelf2Entidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCiudadEntidad)
                    .addComponent(txtCiudadEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioModCiudad))
                .addGap(18, 18, 18)
                .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioModEstado)
                    .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelEstadoEntidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboEstadoEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDirEntidad)
                    .addComponent(txtDirEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioModDir))
                .addGap(26, 26, 26)
                .addGroup(panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardarCambios)
                    .addComponent(botonReestablecer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        getContentPane().add(panelMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 39, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreEntidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEntidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEntidadActionPerformed

    private void txtTelf2EntidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelf2EntidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelf2EntidadActionPerformed

    private void radioModRIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioModRIFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioModRIFActionPerformed

    private void radioModNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioModNombreActionPerformed

    }//GEN-LAST:event_radioModNombreActionPerformed

    private void radioModNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioModNombreMouseClicked
        if(radioModNombre.isSelected()){
            txtNombreEntidad.setEnabled(true);
            txtNombreEntidad.setText(null);
        }
        else{
            txtNombreEntidad.setEnabled(false);
            txtNombreEntidad.setText(entidad.getNombre());
        }
    }//GEN-LAST:event_radioModNombreMouseClicked

    private void radioModRIFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioModRIFMouseClicked
        if(radioModRIF.isSelected()){
            txt8RIFEntidad.setEnabled(true);
            txt1RIFEntidad.setEnabled(true);
            txt8RIFEntidad.setText(null);
            txt1RIFEntidad.setText(null);
        }
        else{
            txt8RIFEntidad.setEnabled(false);
            txt1RIFEntidad.setEnabled(false);
            txt8RIFEntidad.setText(entidad.getRIF().substring(2,9));
            txt1RIFEntidad.setText(entidad.getRIF().substring(11));
        }
    }//GEN-LAST:event_radioModRIFMouseClicked

    private void radioModTelfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioModTelfMouseClicked
        if(radioModTelf.isSelected()){
            txtTelf1Entidad.setEnabled(true);
            txtTelf2Entidad.setEnabled(true);
            txtTelf1Entidad.setText(null);
            txtTelf2Entidad.setText(null);
        }
        else{
            txtTelf1Entidad.setEnabled(false);
            txtTelf2Entidad.setEnabled(false);
            txtTelf1Entidad.setText(entidad.getTelefono().substring(0,3));
            txtTelf2Entidad.setText(entidad.getTelefono().substring(5));
        }
    }//GEN-LAST:event_radioModTelfMouseClicked

    private void radioModCiudadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioModCiudadMouseClicked
        if(radioModCiudad.isSelected()){
            txtCiudadEntidad.setEnabled(true);
            txtCiudadEntidad.setText(null);
        }
        else{
            txtCiudadEntidad.setEnabled(false);
            txtCiudadEntidad.setText(entidad.getCiudad());
        }
    }//GEN-LAST:event_radioModCiudadMouseClicked

    private void radioModEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioModEstadoMouseClicked
        if(radioModEstado.isSelected()) cboEstadoEntidad.setEnabled(true);
        else{
            cboEstadoEntidad.setEnabled(false);
            cboEstadoEntidad.setSelectedItem(entidad.getEstado());
        }
    }//GEN-LAST:event_radioModEstadoMouseClicked

    private void radioModDirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioModDirMouseClicked
        if(radioModDir.isSelected()){
            txtDirEntidad.setEnabled(true);
            txtDirEntidad.setText(null);
        }
        else {
            txtDirEntidad.setEnabled(false);
            txtDirEntidad.setText(entidad.getDireccion());
        }
    }//GEN-LAST:event_radioModDirMouseClicked

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void radioModTelfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioModTelfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioModTelfActionPerformed

    private void botonReestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReestablecerActionPerformed
        controlVentana.entradasModificar_Entidad(entidad,txtNombreEntidad, txt8RIFEntidad, txt1RIFEntidad, txtTelf1Entidad, txtTelf2Entidad, txtCiudadEntidad, cboEstadoEntidad, txtDirEntidad);
        controlVentana.seleccionarBotonesRadio_Entidad(false,radioModNombre, radioModRIF, radioModTelf, radioModCiudad, radioModEstado, radioModDir);
    }//GEN-LAST:event_botonReestablecerActionPerformed

    private void botonGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarCambiosActionPerformed
        if(controlRegistro.confirmar()){
            dispose(); 
            controlVentana.actualizarEntidad(entidad,ventanaAnterior.getLabelNombre_DeLaClinica(),ventanaAnterior.getLabelRIF_DeLaClinica(),ventanaAnterior.getLabelTelf_DeLaClinica(),ventanaAnterior.getLabelCiudad_DeLaClinca(),ventanaAnterior.getLabelEstado_DeLaClinica(),ventanaAnterior.getLabelDir_DeLaClinica());
            ventanaAnterior.setVisible(true);
        }
    }//GEN-LAST:event_botonGuardarCambiosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarEntidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarEntidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarEntidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarEntidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarEntidad().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardarCambios;
    private javax.swing.JButton botonReestablecer;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox<String> cboEstadoEntidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelCiudadEntidad;
    private javax.swing.JLabel labelDirEntidad;
    private javax.swing.JLabel labelEstadoEntidad;
    private javax.swing.JLabel labelNombreEntidad;
    private javax.swing.JLabel labelRIFEntidad;
    private javax.swing.JLabel labelTelfEntidad;
    private javax.swing.JPanel panelMod;
    private javax.swing.JRadioButton radioModCiudad;
    private javax.swing.JRadioButton radioModDir;
    private javax.swing.JRadioButton radioModEstado;
    private javax.swing.JRadioButton radioModNombre;
    private javax.swing.JRadioButton radioModRIF;
    private javax.swing.JRadioButton radioModTelf;
    private javax.swing.JTextField txt1RIFEntidad;
    private javax.swing.JTextField txt8RIFEntidad;
    private javax.swing.JTextField txtCiudadEntidad;
    private javax.swing.JTextField txtDirEntidad;
    private javax.swing.JTextField txtNombreEntidad;
    private javax.swing.JTextField txtTelf1Entidad;
    private javax.swing.JTextField txtTelf2Entidad;
    // End of variables declaration//GEN-END:variables
}
