/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controller.CRegistro;
import Controller.CSistema;
import Controller.CVentana;
import Modelo.Paciente;
import java.time.ZoneId;
import java.util.Date;

/**
 *
 * @author familia
 */
public class ModificarPaciente extends javax.swing.JFrame {
    
    Paciente paciente;
    CVentana controlVentana = new CVentana();
    CRegistro controlRegistro = new CRegistro();
    CSistema controlSistema;
    MenúPrincipal ventanaAnterior;

    /**
     * Creates new form ModificarPaciente
     */
    public ModificarPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        DateFecha = new com.toedter.calendar.JDateChooser();
        boxGenero = new javax.swing.JComboBox<>();
        txtCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jRadioCedula = new javax.swing.JRadioButton();
        jRadioNombre = new javax.swing.JRadioButton();
        jRadioCorreo = new javax.swing.JRadioButton();
        jRadioTelefono = new javax.swing.JRadioButton();
        jRadioFecha = new javax.swing.JRadioButton();
        jRadioGenero = new javax.swing.JRadioButton();
        botonSalir = new javax.swing.JButton();
        botonReestablecer = new javax.swing.JButton();
        botonGuardarCambios = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Cedula : ");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Nombre : ");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Telefono :");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Correo : ");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Genero : ");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Fecha de Nacimiento : ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        boxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        boxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxGeneroActionPerformed(evt);
            }
        });

        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DateFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(boxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCedula)
                    .addComponent(txtNombre)
                    .addComponent(txtCorreo)
                    .addComponent(txtTelefono))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(DateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        jRadioCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioCedulaMouseClicked(evt);
            }
        });
        jRadioCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioCedulaActionPerformed(evt);
            }
        });

        jRadioNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioNombreMouseClicked(evt);
            }
        });
        jRadioNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioNombreActionPerformed(evt);
            }
        });

        jRadioCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioCorreoMouseClicked(evt);
            }
        });
        jRadioCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioCorreoActionPerformed(evt);
            }
        });

        jRadioTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioTelefonoMouseClicked(evt);
            }
        });
        jRadioTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioTelefonoActionPerformed(evt);
            }
        });

        jRadioFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioFechaMouseClicked(evt);
            }
        });
        jRadioFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioFechaActionPerformed(evt);
            }
        });

        jRadioGenero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioGeneroMouseClicked(evt);
            }
        });
        jRadioGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioGeneroActionPerformed(evt);
            }
        });

        botonSalir.setBackground(new java.awt.Color(255, 0, 0));
        botonSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        botonReestablecer.setBackground(new java.awt.Color(51, 255, 0));
        botonReestablecer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonReestablecer.setText("Reestablecer");
        botonReestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReestablecerActionPerformed(evt);
            }
        });

        botonGuardarCambios.setBackground(new java.awt.Color(153, 204, 255));
        botonGuardarCambios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonGuardarCambios.setText("Guardar cambios");
        botonGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarCambiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonSalir))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(botonReestablecer, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonGuardarCambios)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioCedula)
                                            .addComponent(jRadioNombre, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(jRadioCorreo, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jRadioTelefono, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jRadioFecha, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jRadioGenero, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 44, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(botonSalir)
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jRadioCedula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioCorreo)
                                .addGap(24, 24, 24)
                                .addComponent(jRadioTelefono)
                                .addGap(12, 12, 12)
                                .addComponent(jRadioFecha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioGenero))
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonReestablecer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(botonGuardarCambios)))
                .addContainerGap())
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 560, 360));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioCedulaActionPerformed

    private void jRadioNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioNombreActionPerformed

    private void jRadioCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioCorreoActionPerformed

    private void jRadioTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioTelefonoActionPerformed

    private void jRadioFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioFechaActionPerformed

    private void jRadioGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioGeneroActionPerformed

    private void jRadioCedulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioCedulaMouseClicked
        // TODO add your handling code here:
        if(jRadioCedula.isSelected()){
            txtCedula.setEnabled(true);
            txtCedula.setText(null);
        }
        else{
            txtCedula.setEnabled(false);
            txtCedula.setText(paciente.getCedula());
        }
    }//GEN-LAST:event_jRadioCedulaMouseClicked

    private void jRadioNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioNombreMouseClicked
        // TODO add your handling code here:
        if(jRadioNombre.isSelected()){
            txtNombre.setEnabled(true);
            txtNombre.setText(null);
        }
        else{
            txtNombre.setEnabled(false);
            txtNombre.setText(paciente.getNombre());
        }
    }//GEN-LAST:event_jRadioNombreMouseClicked

    private void jRadioCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioCorreoMouseClicked
        // TODO add your handling code here:
        if(jRadioCorreo.isSelected()){
            txtCorreo.setEnabled(true);
            txtCorreo.setText(null);
        }
        else{
            txtCorreo.setEnabled(false);
            txtCorreo.setText(paciente.getCorreo());
        }
    }//GEN-LAST:event_jRadioCorreoMouseClicked

    private void jRadioTelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioTelefonoMouseClicked
        // TODO add your handling code here:
        if(jRadioTelefono.isSelected()){
            txtTelefono.setEnabled(true);
            txtTelefono.setText(null);
        }
        else{
            txtTelefono.setEnabled(false);
            txtTelefono.setText(paciente.getTelefono());
        }
    }//GEN-LAST:event_jRadioTelefonoMouseClicked

    private void jRadioFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioFechaMouseClicked
        // TODO add your handling code here:
        if(jRadioFecha.isSelected()){
            DateFecha.setEnabled(true);
            DateFecha.setDate(null);
        }
        else{
            DateFecha.setEnabled(false);
            ZoneId defaultZoneId = ZoneId.systemDefault();
            DateFecha.setDate(Date.from(paciente.getNacimiento().atStartOfDay(defaultZoneId).toInstant()));
            
        }
    }//GEN-LAST:event_jRadioFechaMouseClicked

    private void boxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxGeneroActionPerformed

    private void jRadioGeneroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioGeneroMouseClicked
        // TODO add your handling code here:
        if(jRadioGenero.isSelected()){
            boxGenero.setEnabled(true);
            boxGenero.setSelectedItem(null);
        }
        else{
            boxGenero.setEnabled(false);            
            boxGenero.setSelectedItem(paciente.getGenero());
        }
    }//GEN-LAST:event_jRadioGeneroMouseClicked

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        dispose();
        ventanaAnterior.setVisible(true);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonReestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReestablecerActionPerformed
        controlVentana.entradasModificar_Paciente(paciente,txtCedula,txtNombre,txtCorreo,txtTelefono,DateFecha,boxGenero);
        controlVentana.seleccionarBotonesRadio_Entidad(false,jRadioCedula,jRadioNombre,jRadioCorreo,jRadioTelefono,jRadioFecha,jRadioGenero);
    }//GEN-LAST:event_botonReestablecerActionPerformed

    private void botonGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarCambiosActionPerformed
//        boolean validaciones = && controlRegistro.validarRIF(txt1RIFEntidad,1) && controlRegistro.validarTelf(txtTelf1Entidad,4) && controlRegistro.validarTelf(txtTelf2Entidad,7) && controlRegistro.validarNombre(txtCiudadEntidad);
//        if(validaciones && controlRegistro.camposVaciosEntidad(txtNombreEntidad, txt8RIFEntidad, txt1RIFEntidad, txtTelf1Entidad, txtTelf2Entidad, txtDirEntidad, txtDirEntidad)==false){
//            boolean modRIF=false,modTelf=false,continuar=true;
//            String RIF = controlRegistro.construirRIF(txt8RIFEntidad, txt1RIFEntidad);
//            String telf = controlRegistro.construirTelf(txtTelf1Entidad, txtTelf2Entidad);
//            if(!RIF.equals(entidad.getRIF())) modRIF=true;
//            if(!telf.equals(entidad.getTelefono())) modTelf=true;
//
//            if(modRIF==true && controlSistema.seEncuentraRegistrada_RIF(RIF,false)) continuar=false;
//            if(modTelf==true && controlSistema.seEncuentraRegistrada_Telf(telf)) continuar=false;
//
//            if(continuar){
//                if(controlRegistro.confirmar()){
//                    dispose();
//                    controlRegistro.actualizarEntidad(entidad,txtNombreEntidad,RIF,telf,txtCiudadEntidad,cboEstadoEntidad,txtDirEntidad);
//                    if(entidad instanceof Clinica) controlRegistro.actualizarEtiquetas_Entidad(entidad,ventanaAnterior.getLabelNombre_DeLaClinica(),ventanaAnterior.getLabelRIF_DeLaClinica(),ventanaAnterior.getLabelTelf_DeLaClinica(),ventanaAnterior.getLabelCiudad_DeLaClinca(),ventanaAnterior.getLabelEstado_DeLaClinica(),ventanaAnterior.getLabelDir_DeLaClinica());
//                    if(entidad instanceof Ambulatorio) controlRegistro.actualizarEtiquetas_Entidad(entidad,ventanaAnterior.getLabelNombre_DelAmbulatorio(),ventanaAnterior.getLabelRIF_DelAmbulatorio(),ventanaAnterior.getLabelTelf_DelAmbulatorio(),ventanaAnterior.getLabelCiudad_DelAmbulatorio(),ventanaAnterior.getLabelEstado_DelAmbulatorio(),ventanaAnterior.getLabelDir_DelAmbulatorio());
//                    ventanaAnterior.setVisible(true);
//                }
//            }
//        }
    }//GEN-LAST:event_botonGuardarCambiosActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateFecha;
    private javax.swing.JButton botonGuardarCambios;
    private javax.swing.JButton botonReestablecer;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox<String> boxGenero;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRadioCedula;
    private javax.swing.JRadioButton jRadioCorreo;
    private javax.swing.JRadioButton jRadioFecha;
    private javax.swing.JRadioButton jRadioGenero;
    private javax.swing.JRadioButton jRadioNombre;
    private javax.swing.JRadioButton jRadioTelefono;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
