
package Vista;

import Controller.*;
import Modelo.*;
import com.toedter.calendar.JTextFieldDateEditor;
import java.util.*;

public class PantallaRegistrarMantenimiento extends javax.swing.JFrame {
    CVehiculo con;
    MenúPrincipal ventanaAnterior;
    CVentana controlVentana = new CVentana(this);
    CRegistro conR = new CRegistro();
    
    public PantallaRegistrarMantenimiento() {
        initComponents();
    }
    
    public PantallaRegistrarMantenimiento(CVehiculo con,MenúPrincipal ventanaAnterior) {
        initComponents();
        this.con = con;
        this.ventanaAnterior = ventanaAnterior;
        controlVentana.iniciarVentana(this,"src/imagenes/logo(1).png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMovimientos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonSalir = new javax.swing.JButton();
        labelSalida = new javax.swing.JLabel();
        labelEntrada = new javax.swing.JLabel();
        labelTaller = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        fechaEntrada = new com.toedter.calendar.JDateChooser();
        fechaSalida = new com.toedter.calendar.JDateChooser();
        txtTaller = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnRegistrarM = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMovimientos.setBackground(new java.awt.Color(255, 255, 255));
        panelMovimientos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Datos del mantenimiento");
        panelMovimientos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 320, 50));

        botonSalir.setBackground(new java.awt.Color(255, 0, 0));
        botonSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        panelMovimientos.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 120, 50));

        labelSalida.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelSalida.setText("Salida:");
        panelMovimientos.add(labelSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, 20));

        labelEntrada.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelEntrada.setText("Entrada:");
        panelMovimientos.add(labelEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, 20));

        labelTaller.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTaller.setText("Taller (RIF):");
        panelMovimientos.add(labelTaller, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, 20));

        labelDescripcion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelDescripcion.setText("Descripcion:");
        panelMovimientos.add(labelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, 20));
        panelMovimientos.add(fechaEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 200, -1));
        JTextFieldDateEditor editor1 = (JTextFieldDateEditor) fechaEntrada.getDateEditor();
        editor1.setEditable(false);
        panelMovimientos.add(fechaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 200, 30));
        JTextFieldDateEditor editor2 = (JTextFieldDateEditor) fechaSalida.getDateEditor();
        editor2.setEditable(false);

        txtTaller.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTallerFocusLost(evt);
            }
        });
        panelMovimientos.add(txtTaller, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 230, 30));

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        panelMovimientos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 290, 100));

        btnRegistrarM.setBackground(new java.awt.Color(0, 102, 255));
        btnRegistrarM.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRegistrarM.setText("Registrar");
        btnRegistrarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarMActionPerformed(evt);
            }
        });
        panelMovimientos.add(btnRegistrarM, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 150, 40));

        getContentPane().add(panelMovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 740, 480));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        dispose();
        ventanaAnterior.setVisible(true);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void btnRegistrarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarMActionPerformed
        con.registrarManenimiento(fechaEntrada.getDate(), fechaSalida.getDate(), txtTaller.getText(), txtDescripcion.getText());
    }//GEN-LAST:event_btnRegistrarMActionPerformed

    private void txtTallerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTallerFocusLost
        if (!conR.formatoRIFCompleto(txtTaller.getText())){
            txtTaller.setText(null);
        }
    }//GEN-LAST:event_txtTallerFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistrarMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistrarMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistrarMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistrarMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaRegistrarMantenimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton btnRegistrarM;
    private com.toedter.calendar.JDateChooser fechaEntrada;
    private com.toedter.calendar.JDateChooser fechaSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelEntrada;
    private javax.swing.JLabel labelSalida;
    private javax.swing.JLabel labelTaller;
    private javax.swing.JPanel panelMovimientos;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtTaller;
    // End of variables declaration//GEN-END:variables
}
