/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controller.CInventario;
import Modelo.Suministro;
import com.toedter.calendar.JTextFieldDateEditor;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo Consalvo
 */
public class PantallaInventario extends javax.swing.JFrame {
    Suministro sum;
    CInventario con = new CInventario();
    /**
     * Creates new form pruebaUnidades
     */
    public PantallaInventario() {
        initComponents();
        sum = new Suministro();
        con.mostrarUnidades(tablaUnidades, tituloTabla, sum);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUnidades = new javax.swing.JTable();
        tituloTabla = new javax.swing.JLabel();
        calendario = new com.toedter.calendar.JDateChooser();
        tipoMovimiento = new javax.swing.JComboBox<>();
        btnSeleccionarUni = new javax.swing.JButton();
        label1Movimientos = new javax.swing.JLabel();
        txtNEmergenciaArgumento = new javax.swing.JTextField();
        label2Movimientos = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaObjetos = new javax.swing.JList<>();
        combo1Movimientos = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaUnidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(tablaUnidades);
        tablaUnidades.setEnabled(false);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 58, 375, 110));

        tituloTabla.setText("Titulo tabla");
        getContentPane().add(tituloTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 20, 133, 32));
        Calendar calendar = Calendar.getInstance();
        calendar.add(Calendar.DAY_OF_YEAR, 1);

        calendario.setDateFormatString("dd/MM/yyyy");
        calendario.setMinSelectableDate(calendar.getTime()
        );
        getContentPane().add(calendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 215, -1));
        JTextFieldDateEditor editor = (JTextFieldDateEditor) calendario.getDateEditor();
        editor.setEditable(false);

        tipoMovimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrada", "Salida", "Reubicacion" }));
        tipoMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoMovimientoActionPerformed(evt);
            }
        });
        getContentPane().add(tipoMovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 134, 32));

        btnSeleccionarUni.setText("Seleccionar Unidad");
        btnSeleccionarUni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarUniActionPerformed(evt);
            }
        });
        getContentPane().add(btnSeleccionarUni, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 151, 41));
        btnSeleccionarUni.setEnabled(false);

        label1Movimientos.setText("Fecha de vencimiento:");
        getContentPane().add(label1Movimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 140, 28));
        getContentPane().add(txtNEmergenciaArgumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 128, -1));
        txtNEmergenciaArgumento.setVisible(false);

        label2Movimientos.setText("Cantidad:");
        getContentPane().add(label2Movimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 120, 30));
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 40, -1));

        jScrollPane2.setViewportView(listaObjetos);
        listaObjetos.setVisible(false);
        listaObjetos.setEnabled(false);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 60, 100));
        jScrollPane2.setVisible(false);

        combo1Movimientos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aplica", "No aplica" }));
        getContentPane().add(combo1Movimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 120, -1));

        btnRegistrar.setText("Registrar ");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 150, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoMovimientoActionPerformed
        // TODO add your handling code here:
        switch (tipoMovimiento.getSelectedIndex()){
            case 0: //Entrada
                con.tipoMovimientoEntrada(tablaUnidades, btnSeleccionarUni, label1Movimientos, calendario, combo1Movimientos, txtNEmergenciaArgumento, label2Movimientos, txtCantidad, listaObjetos, jScrollPane2);
            break;
            
            case 1: //Salida
                con.tipoMovimientoSalida(tablaUnidades, btnSeleccionarUni, label1Movimientos, calendario, combo1Movimientos, txtNEmergenciaArgumento, label2Movimientos, txtCantidad, listaObjetos, jScrollPane2);
            break;
            
            case 2: //Reubicación
                con.tipoMovimientoReubicacion(tablaUnidades, btnSeleccionarUni, label1Movimientos, calendario, combo1Movimientos, txtNEmergenciaArgumento, label2Movimientos, txtCantidad, listaObjetos, jScrollPane2);
            break;
        }
    }//GEN-LAST:event_tipoMovimientoActionPerformed

    private void btnSeleccionarUniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarUniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionarUniActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSeleccionarUni;
    private com.toedter.calendar.JDateChooser calendario;
    private javax.swing.JComboBox<String> combo1Movimientos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label1Movimientos;
    private javax.swing.JLabel label2Movimientos;
    private javax.swing.JList<String> listaObjetos;
    private javax.swing.JTable tablaUnidades;
    private javax.swing.JComboBox<String> tipoMovimiento;
    private javax.swing.JLabel tituloTabla;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtNEmergenciaArgumento;
    // End of variables declaration//GEN-END:variables
}
