/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controller.*;
import Modelo.Clinica;
import java.awt.Color;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.*;

/**
 *
 * @author jdfer
 */
public class PantallaRegistro extends javax.swing.JFrame {
    private IniciarSesión iniciarSesion;
    CRegistro controlRegistro;
    CSistema controlSistema;
    CVentana controlVentana;
    /**
     * Creates new form Pantalla_de_inicio
     */
    public PantallaRegistro() {
        initComponents();

    }
    
    public PantallaRegistro(CSistema controlSistema,IniciarSesión iniciarSesion){
        initComponents();
        this.iniciarSesion = iniciarSesion;
        this.controlSistema=controlSistema;
        controlRegistro = new CRegistro();
        controlVentana = new CVentana();
        controlVentana.iniciarVentana(this,"src/imagenes/logo(1).png");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRegistro = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        botonRegistrar = new javax.swing.JButton();
        labelNombreClinica = new javax.swing.JLabel();
        txtNombreClinica = new javax.swing.JTextField();
        labelRIF = new javax.swing.JLabel();
        labelCiudad = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        labelDir = new javax.swing.JLabel();
        txtDir = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt8RIF = new javax.swing.JTextField();
        txt1RIF = new javax.swing.JTextField();
        labelTelf = new javax.swing.JLabel();
        txtTelf1 = new javax.swing.JTextField();
        guion2 = new javax.swing.JLabel();
        txtTelf2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cboEstado = new javax.swing.JComboBox<>();
        botonVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRegistro.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N

        botonRegistrar.setBackground(new java.awt.Color(153, 204, 255));
        botonRegistrar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botonRegistrar.setText("Registrar clínica");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        labelNombreClinica.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelNombreClinica.setText("Nombre de la clínica:");

        txtNombreClinica.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNombreClinica.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreClinicaFocusLost(evt);
            }
        });
        txtNombreClinica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClinicaActionPerformed(evt);
            }
        });

        labelRIF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelRIF.setText("RIF:   J-");

        labelCiudad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelCiudad.setText("Ciudad:");

        txtCiudad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCiudad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCiudadFocusLost(evt);
            }
        });

        labelDir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelDir.setText("Dirección:");

        txtDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("-");

        txt8RIF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt8RIF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt8RIFFocusLost(evt);
            }
        });
        txt8RIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt8RIFActionPerformed(evt);
            }
        });

        txt1RIF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt1RIF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt1RIFFocusLost(evt);
            }
        });

        labelTelf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTelf.setText("Teléfono:");

        txtTelf1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTelf1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelf1FocusLost(evt);
            }
        });
        txtTelf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelf1ActionPerformed(evt);
            }
        });

        guion2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        guion2.setText("-");

        txtTelf2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTelf2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelf2FocusLost(evt);
            }
        });
        txtTelf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelf2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Estado:");

        cboEstado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amazonas", "Anzoátegui", "Apure", "Aragua", "Barinas", "Bolívar", "Carabobo", "Cojedes", "Delta Amacuro", "Falcón", "Guárico", "Lara", "Mérida", "Miranda", "Monagas", "Nueva Esparta", "Portuguesa", "Sucre", "Táchira", "Trujillo", "Vargas", "Yaracuy", "Zulia" }));
        cboEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRegistroLayout = new javax.swing.GroupLayout(panelRegistro);
        panelRegistro.setLayout(panelRegistroLayout);
        panelRegistroLayout.setHorizontalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logo)
                .addGap(136, 136, 136))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonRegistrar)
                .addGap(135, 135, 135))
            .addGroup(panelRegistroLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistroLayout.createSequentialGroup()
                        .addComponent(labelTelf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTelf1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guion2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelf2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelRegistroLayout.createSequentialGroup()
                            .addComponent(labelCiudad)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelRegistroLayout.createSequentialGroup()
                            .addComponent(labelDir)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtDir))
                        .addGroup(panelRegistroLayout.createSequentialGroup()
                            .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelRegistroLayout.createSequentialGroup()
                                    .addComponent(labelRIF)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt8RIF, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(labelNombreClinica))
                            .addGap(6, 6, 6)
                            .addComponent(jLabel2)
                            .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelRegistroLayout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(txtNombreClinica, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelRegistroLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt1RIF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelRegistroLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        panelRegistroLayout.setVerticalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addGap(35, 35, 35)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreClinica)
                    .addComponent(txtNombreClinica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRIF)
                    .addComponent(jLabel2)
                    .addComponent(txt8RIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt1RIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTelf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTelf2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(guion2))
                    .addComponent(labelTelf))
                .addGap(21, 21, 21)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCiudad)
                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDir)
                    .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonRegistrar)
                .addGap(27, 27, 27))
        );

        getContentPane().add(panelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 500, 570));

        botonVolver.setBackground(new java.awt.Color(255, 0, 51));
        botonVolver.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(botonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        iniciarSesion.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void txtNombreClinicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClinicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClinicaActionPerformed

    private void txtDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirActionPerformed

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        if(controlRegistro.camposVaciosEntidad(txtNombreClinica,txt8RIF,txt1RIF,txtTelf1,txtTelf2,txtCiudad,txtDir)==false){
            String RIF = controlRegistro.construirRIF(txt8RIF,txt1RIF);
            String telf = controlRegistro.construirTelf(txtTelf1,txtTelf2);
            if(controlSistema.seEncuentraRegistrada_RIF(RIF,false)==false && controlSistema.seEncuentraRegistrada_Telf(telf)==false){
                if(controlRegistro.confirmar()==true){
                    controlSistema.crearClinica(txtNombreClinica.getText(),RIF,telf,txtCiudad.getText(),cboEstado.getSelectedItem().toString(),txtDir.getText());
                    iniciarSesion.setVisible(true);
                    dispose();
                }                   
            }
        }
    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void txt8RIFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt8RIFFocusLost
        // TODO add your handling code here:
        if(controlRegistro.validarRIF(txt8RIF,8)==false) txt8RIF.setText(null);
    }//GEN-LAST:event_txt8RIFFocusLost

    private void txt1RIFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt1RIFFocusLost
        // TODO add your handling code here:
        if(controlRegistro.validarRIF(txt1RIF,1)==false) txt1RIF.setText(null);
    }//GEN-LAST:event_txt1RIFFocusLost

    private void txtTelf1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelf1FocusLost
        // TODO add your handling code here:
        if(controlRegistro.validarTelf(txtTelf1,4)==false) txtTelf1.setText(null);
    }//GEN-LAST:event_txtTelf1FocusLost

    private void txtTelf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelf1ActionPerformed

    private void txtTelf2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelf2FocusLost
        // TODO add your handling code here:
        if(controlRegistro.validarTelf(txtTelf2,7)==false) txtTelf2.setText(null);
    }//GEN-LAST:event_txtTelf2FocusLost

    private void txtTelf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelf2ActionPerformed

    private void cboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEstadoActionPerformed

    private void txtNombreClinicaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreClinicaFocusLost
        // TODO add your handling code here:
        if(controlRegistro.validarNombreEntidad(txtNombreClinica)==false) txtNombreClinica.setText(null);
    }//GEN-LAST:event_txtNombreClinicaFocusLost

    private void txtCiudadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCiudadFocusLost
        if(controlRegistro.validarNombre(txtCiudad)==false) txtCiudad.setText(null);
    }//GEN-LAST:event_txtCiudadFocusLost

    private void txt8RIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt8RIFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt8RIFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JButton botonVolver;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JLabel guion2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelCiudad;
    private javax.swing.JLabel labelDir;
    private javax.swing.JLabel labelNombreClinica;
    private javax.swing.JLabel labelRIF;
    private javax.swing.JLabel labelTelf;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panelRegistro;
    private javax.swing.JTextField txt1RIF;
    private javax.swing.JTextField txt8RIF;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtDir;
    private javax.swing.JTextField txtNombreClinica;
    private javax.swing.JTextField txtTelf1;
    private javax.swing.JTextField txtTelf2;
    // End of variables declaration//GEN-END:variables
}
