
package Vista;

import Controller.*;
import Modelo.*;
import java.util.*;
import javax.swing.JOptionPane;

public class PantallaVerMovimientos extends javax.swing.JFrame {
    Suministro sum;
    CInventario con;
    PantallaDetalleSum ventanaAnterior;
    CVentana controlVentana = new CVentana(this);
    
    public PantallaVerMovimientos() {
        initComponents();
    }
    
    public PantallaVerMovimientos(Suministro sum, CInventario con,PantallaDetalleSum ventanaAnterior) {
        this.sum = sum;
        initComponents();
        this.con = con;
        this.ventanaAnterior = ventanaAnterior;
        con.mostrarMovimientos(sum, tablaEntradas, tablaSalidas, tablaReubicaciones);
        controlVentana.iniciarVentana(this,"src/imagenes/logo(1).png");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMovimientos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonSalir = new javax.swing.JButton();
        tituloTabla = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSalidas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaReubicaciones = new javax.swing.JTable();
        tituloTabla1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaEntradas = new javax.swing.JTable();
        tituloTabla2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMovimientos.setBackground(new java.awt.Color(255, 255, 255));
        panelMovimientos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Movimientos de: "+sum.getNombre());
        panelMovimientos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 320, 50));

        botonSalir.setBackground(new java.awt.Color(255, 0, 0));
        botonSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonSalir.setText("Volver");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        panelMovimientos.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 120, 50));

        tituloTabla.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tituloTabla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloTabla.setText("Salidas");
        panelMovimientos.add(tituloTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 250, 32));

        tablaSalidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tablaSalidas.setRowHeight(30);
        tablaSalidas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaSalidas);

        panelMovimientos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 370, 180));

        tablaReubicaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tablaReubicaciones.setRowHeight(30);
        tablaReubicaciones.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablaReubicaciones);

        panelMovimientos.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 570, 180));

        tituloTabla1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tituloTabla1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloTabla1.setText("Reubicaciones");
        panelMovimientos.add(tituloTabla1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 250, 32));

        tablaEntradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tablaEntradas.setRowHeight(30);
        tablaEntradas.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tablaEntradas);

        panelMovimientos.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 370, 180));

        tituloTabla2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tituloTabla2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloTabla2.setText("Entradas");
        panelMovimientos.add(tituloTabla2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 250, 32));

        getContentPane().add(panelMovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 830, 610));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        dispose();
        ventanaAnterior.setVisible(true);
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaVerMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaVerMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaVerMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaVerMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaVerMovimientos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelMovimientos;
    private javax.swing.JTable tablaEntradas;
    private javax.swing.JTable tablaReubicaciones;
    private javax.swing.JTable tablaSalidas;
    private javax.swing.JLabel tituloTabla;
    private javax.swing.JLabel tituloTabla1;
    private javax.swing.JLabel tituloTabla2;
    // End of variables declaration//GEN-END:variables
}
