
package Vista;

import Controller.*;
import Modelo.*;
import com.toedter.calendar.JTextFieldDateEditor;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;

public class PantallaRegistrarMantenimiento extends javax.swing.JFrame {
    CVehiculo con;
    MenúPrincipal ventanaAnterior;
    CVentana controlVentana = new CVentana(this);
    CRegistro conR = new CRegistro();
    CClinica conCli;
    JTable tablaMant;
    
    public PantallaRegistrarMantenimiento() {
        initComponents();
    }
    
    public PantallaRegistrarMantenimiento(CVehiculo con,CClinica conCli,JTable tablaMant,MenúPrincipal ventanaAnterior) {
        initComponents();
        this.con = con;
        this.conCli = conCli;
        this.tablaMant = tablaMant;
        this.ventanaAnterior = ventanaAnterior;
        controlVentana.iniciarVentana(this,"src/imagenes/logo(1).png");
        con.ventanaMantenimiento(txt1RifTaller,txt2RifTaller,txtDescripcion,fechaEntrada,cboEstado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMovimientos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonSalir = new javax.swing.JButton();
        labelSalida = new javax.swing.JLabel();
        labelEntrada = new javax.swing.JLabel();
        labelTaller = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        fechaEntrada = new com.toedter.calendar.JDateChooser();
        fechaSalida = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnRegistrarM = new javax.swing.JButton();
        txt1RifTaller = new javax.swing.JTextField();
        txt2RifTaller = new javax.swing.JTextField();
        labelTaller1 = new javax.swing.JLabel();
        cboEstado = new javax.swing.JComboBox<>();
        labelEntrada1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMovimientos.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Datos del mantenimiento");

        botonSalir.setBackground(new java.awt.Color(255, 0, 0));
        botonSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        labelSalida.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelSalida.setText("Salida:");

        labelEntrada.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelEntrada.setText("Entrada:");

        labelTaller.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTaller.setText("-");

        labelDescripcion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelDescripcion.setText("Descripcion:");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        btnRegistrarM.setBackground(new java.awt.Color(0, 102, 255));
        btnRegistrarM.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRegistrarM.setText("Registrar");
        btnRegistrarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarMActionPerformed(evt);
            }
        });

        txt1RifTaller.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt1RifTaller.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt1RifTallerFocusLost(evt);
            }
        });

        txt2RifTaller.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt2RifTaller.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt2RifTallerFocusLost(evt);
            }
        });

        labelTaller1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTaller1.setText("Taller (RIF): J -");

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En progreso", "Finalizado" }));
        cboEstado.setSelectedIndex(1);
        cboEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEstadoActionPerformed(evt);
            }
        });

        labelEntrada1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelEntrada1.setText("Estado:");

        javax.swing.GroupLayout panelMovimientosLayout = new javax.swing.GroupLayout(panelMovimientos);
        panelMovimientos.setLayout(panelMovimientosLayout);
        panelMovimientosLayout.setHorizontalGroup(
            panelMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMovimientosLayout.createSequentialGroup()
                .addGroup(panelMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMovimientosLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190)
                        .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMovimientosLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(labelDescripcion)
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMovimientosLayout.createSequentialGroup()
                        .addGap(560, 560, 560)
                        .addComponent(btnRegistrarM, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMovimientosLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(panelMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMovimientosLayout.createSequentialGroup()
                                .addComponent(labelTaller1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt1RifTaller, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelTaller, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt2RifTaller, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelMovimientosLayout.createSequentialGroup()
                                .addComponent(labelSalida)
                                .addGap(18, 18, 18)
                                .addComponent(fechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelMovimientosLayout.createSequentialGroup()
                                .addComponent(labelEntrada)
                                .addGap(18, 18, 18)
                                .addComponent(fechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelMovimientosLayout.createSequentialGroup()
                                .addComponent(labelEntrada1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panelMovimientosLayout.setVerticalGroup(
            panelMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMovimientosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelMovimientosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEntrada1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panelMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelTaller1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt1RifTaller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt2RifTaller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelTaller, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(panelMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(btnRegistrarM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JTextFieldDateEditor editor1 = (JTextFieldDateEditor) fechaEntrada.getDateEditor();
        editor1.setEditable(false);
        JTextFieldDateEditor editor2 = (JTextFieldDateEditor) fechaSalida.getDateEditor();
        editor2.setEditable(false);

        getContentPane().add(panelMovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 740, 480));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        dispose();
        ventanaAnterior.setVisible(true);
        ventanaAnterior.controlVehiculo.mostrarMantenimiento(tablaMant);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void btnRegistrarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarMActionPerformed
        try{
        if (conCli.tallerRegistrado(conR.construirRIF(txt1RifTaller, txt2RifTaller))){
            con.registrarManenimiento(fechaEntrada.getDate(), fechaSalida.getDate(), conR.construirRIF(txt1RifTaller, txt2RifTaller), txtDescripcion.getText(),cboEstado);
            if (cboEstado.getSelectedIndex()==1){
                txt1RifTaller.setText(null);
                txt2RifTaller.setText(null);
                txtDescripcion.setText(null);
                fechaEntrada.setDate(null);
                fechaSalida.setDate(null);
                txt1RifTaller.setEnabled(true);
                txt2RifTaller.setEnabled(true);
                txtDescripcion.setEnabled(true);
                fechaEntrada.setEnabled(true);
                fechaSalida.setEnabled(true);
                cboEstado.setEnabled(true);
            }else{
                txt1RifTaller.setEnabled(false);
                txt2RifTaller.setEnabled(false);
                txtDescripcion.setEnabled(false);
                fechaEntrada.setEnabled(false);
                fechaSalida.setEnabled(true);
                cboEstado.setSelectedIndex(1);
                cboEstado.setEnabled(false);
            }
        }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Debe llenar todos los datos correctamente", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarMActionPerformed

    private void txt1RifTallerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt1RifTallerFocusLost
        // TODO add your handling code here:
        if(conR.validarRIF(txt1RifTaller,8)==false) txt1RifTaller.setText(null);
    }//GEN-LAST:event_txt1RifTallerFocusLost

    private void txt2RifTallerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt2RifTallerFocusLost
        // TODO add your handling code here:
        if(conR.validarRIF(txt2RifTaller,1)==false) txt2RifTaller.setText(null);
    }//GEN-LAST:event_txt2RifTallerFocusLost

    private void cboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEstadoActionPerformed
        con.estadoMantenimiento(cboEstado,fechaSalida);
    }//GEN-LAST:event_cboEstadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistrarMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistrarMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistrarMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistrarMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaRegistrarMantenimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton btnRegistrarM;
    private javax.swing.JComboBox<String> cboEstado;
    private com.toedter.calendar.JDateChooser fechaEntrada;
    private com.toedter.calendar.JDateChooser fechaSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelEntrada;
    private javax.swing.JLabel labelEntrada1;
    private javax.swing.JLabel labelSalida;
    private javax.swing.JLabel labelTaller;
    private javax.swing.JLabel labelTaller1;
    private javax.swing.JPanel panelMovimientos;
    private javax.swing.JTextField txt1RifTaller;
    private javax.swing.JTextField txt2RifTaller;
    private javax.swing.JTextArea txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
