
package Vista;

import Controller.*;
import Modelo.*;
import java.util.*;
import javax.swing.JOptionPane;

public class PantallaDetalleSum extends javax.swing.JFrame {
    Suministro sum;
    CInventario con = new CInventario(new Ambulatorio());
    MenúPrincipal ventanaAnterior;
    CVentana controlVentana = new CVentana(this);
    
    public PantallaDetalleSum() {
        sum = new Suministro("Medicamento","Atamel","Acetaminofen 20mg");
        Unidad uni1 = new Unidad("Almacen","26/07/2021");
        Unidad uni2 = new Unidad("Ambulancia 1","04/09/2021");
        sum.getUnidades().add(uni1);
        sum.getUnidades().add(uni2);
        initComponents();
        con.mostrarUnidades(tablaUnidades, tituloTabla, sum);
    }
    
    public PantallaDetalleSum(Suministro sum, CInventario con,MenúPrincipal ventanaAnterior) {
        this.sum = sum;
        initComponents();
        this.con = con;
        this.ventanaAnterior = ventanaAnterior;
        con.mostrarUnidades(tablaUnidades, tituloTabla, sum);
        controlVentana.iniciarVentana(this,"src/imagenes/logo(1).png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMovimientos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonSalir = new javax.swing.JButton();
        labelCodigo = new javax.swing.JLabel();
        descripcion = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelTipo = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();
        codigo = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        tituloTabla = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUnidades = new javax.swing.JTable();
        btnVerMov = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMovimientos.setBackground(new java.awt.Color(255, 255, 255));
        panelMovimientos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Informacion del suministro");
        panelMovimientos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 320, 50));

        botonSalir.setBackground(new java.awt.Color(255, 0, 0));
        botonSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        panelMovimientos.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 120, 50));

        labelCodigo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelCodigo.setText("Código:");
        panelMovimientos.add(labelCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, 20));

        descripcion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        descripcion.setText(sum.getDescripción());
        panelMovimientos.add(descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 410, 20));

        labelNombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelNombre.setText("Nombre:");
        panelMovimientos.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, 20));

        labelTipo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTipo.setText("Tipo:");
        panelMovimientos.add(labelTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, 20));

        labelDescripcion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelDescripcion.setText("Descripcion:");
        panelMovimientos.add(labelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, 20));

        tipo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tipo.setText(sum.getTipo());
        panelMovimientos.add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 410, 20));

        codigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        String cod = String.valueOf(sum.getCodigo());
        if (cod.length()==1)
        cod="00"+cod;
        else if (cod.length()==2)
        cod="0"+cod;
        codigo.setText(cod);
        panelMovimientos.add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 410, 20));

        nombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nombre.setText(sum.getNombre());
        panelMovimientos.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 410, 20));

        tituloTabla.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tituloTabla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloTabla.setText("Titulo tabla");
        panelMovimientos.add(tituloTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 250, 32));
        Calendar calendar = Calendar.getInstance();
        calendar.add(Calendar.DAY_OF_YEAR, 1);

        tablaUnidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tablaUnidades.setRowHeight(30);
        tablaUnidades.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaUnidades);
        tablaUnidades.setEnabled(false);

        panelMovimientos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 580, 180));

        btnVerMov.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btnVerMov.setText("Ver movimientos");
        btnVerMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerMovActionPerformed(evt);
            }
        });
        panelMovimientos.add(btnVerMov, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, 200, 50));

        getContentPane().add(panelMovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 740, 610));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        dispose();
        ventanaAnterior.setVisible(true);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void btnVerMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMovActionPerformed
        PantallaVerMovimientos pantallaMovimientos = new PantallaVerMovimientos(sum, con, this);
        setVisible(false);
        pantallaMovimientos.setVisible(true);
    }//GEN-LAST:event_btnVerMovActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaDetalleSum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaDetalleSum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaDetalleSum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaDetalleSum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaDetalleSum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton btnVerMov;
    private javax.swing.JLabel codigo;
    private javax.swing.JLabel descripcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JLabel nombre;
    private javax.swing.JPanel panelMovimientos;
    private javax.swing.JTable tablaUnidades;
    private javax.swing.JLabel tipo;
    private javax.swing.JLabel tituloTabla;
    // End of variables declaration//GEN-END:variables
}
